### ISSUE TITLE
Deploy jore4-hastus microservice

### ISSUE THREAD

**Issue by pallost** [HSLdevcom/jore4#1009]
- [ ] Should make sure that the docker interface is documented in the repository's README.md
- [ ] Should create the flux configuration in jore4-flux repository (see the flux repo README)
- [ ] Question: how do we handle the hasura authentication for the hastus microservice? Is there such concept as "machine user"? Most probably this will need changes in the auth backend too (Split to a separate ticket if necessary)

**Comment by jschummer** [comment]
About the Hasura access: Most probably the issue can be solved by adopting the auth-backend (if needed). If there is bigger issues with granting access, keep in mind that also straight db access may be an option.

**Comment by jschummer** [comment]
In addition to the suggestions from @jarkkoka , also forwarding the user's Hasura auth via the jore4-hastus-backend may be an option (the same way as the user auth is sent to Hasura when the UI sends direct Hasura requests, but in this case the jore4-hastus backend would forward those headers).

**Comment by jschummer** [comment]
This has apparently been implemented at least partially? @culka
