### ISSUE TITLE
As a public transport planner I want to upload different timetables for a day

### ISSUE THREAD

**Issue by ossiberg** [HSLdevcom/jore4#101]
Some special day, an example: Östersundom skola has a school day on Saturday 13.3.2021, which requires that route 91 and 91K runs some additional departures on that specific day.

--

Conclusions from the discussion: 
1) The codes for established special days can be handled "under the hood" or be more explicit on the settings page
2) New special days done using a code require the code to be displayed/edited. [Example in Figma](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=3054%3A217992).

**Comment by juhakolari** [comment]
@ossiberg 

A clarification: 
1) Can Hastus export these day-specific timetables and it's a matter of JORE 4 being able to import them?
_or_ 
2) Hastus is not able to export with such specificity and the valid day needs to be set in the Jore Hastus import preview? 

If 2), this seems like a feature that can be resolved with [a modified validity period setting in the save dialog](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=3005%3A207897) (Figma) that was earlier considered as unnecessary for timetables.

**Comment by ossiberg** [comment]
@juhakolari 

1. is the right one. There are two options:
- Cut validity of basic version so that one-day timetables are only ones valid (done quite infrequently)
- Add a special day code to schedules and upload them to Jore. If no special day exists (such as IP = itsenäisyyspäivä), then it is required to first add a special day in Jore and map it to the date. (typically done this way)
