### ISSUE TITLE
Create E2E test automation for exporting a sample line to Hastus

### ISSUE THREAD

**Issue by pallost** [HSLdevcom/jore4#1010]
As the jore4-hastus microservice heavily depends on the datamodel defined by hasura, we need an E2E test that checks whether these two microservices are compatible. This test need to be an e2e test, because it needs to be executed when:
1. we want to check that the new version of jore4-hastus is compatible with the current bundled version of hasura 
2. we want to check that the new version of hasura is compatible with the current bundled version of jore4-hastus 
3. when creating a new dev/e2e/etc bundle, these two microservices are updated and compatible

The test could consist of:
1. creating a mock data of a line with some routes and stops
2. clicking through a UI to export the given line to hastus
3. check the contents of the generated csv on a very high level that it makes sense. (The detailed csv content checking happens in the jore4-hastus repository's integration tests)

**Comment by sr-vala** [comment]
Will proceed after the bug in the feature is fixed.
