### ISSUE TITLE
Create application users in Postgresql database || L-XL

### ISSUE THREAD

**Issue by pallost** [HSLdevcom/jore4#103]
As a Developer, I would like to access the database through a non-superadmin user.

When the SQL database is created, we only have the superadmin credentials for the database. It's needed to create users with limited access rights for the different applications, like Hasura, Reittikartta, etc.

**Comment by pallost** [comment]
It's currently a bit of a challenge, because after the database is created to the private subnet, it cannot be accessed from outside, only through a bastion host. It's accessible however through Kubernetes pods of course.

There supposed to be an Azure CLI command which _might_ allow us to connect to the database directly, without bastion host. See https://docs.microsoft.com/en-us/azure/postgresql/flexible-server/connect-azure-cli . Unfortunately the `rdbms-connect` extension it uses internally seems to be broken as it cannot be installed. :)

Another idea is to have a specialized docker container in Kubernetes whose sole purpose is to run migrations in the database; this container would have access to the superadmin credentials to be able to create the application users.

Another idea would be to use a Kubernetes job, but I don't know enough yet on how that could be executed through ansible... maybe with some `kubectl apply -f https://raw.githubusercontent.com/HSLdevcom/jore4-deploy/main/kubernetes/jore4-basic-users-job.yml` magic...?

**Comment by haphut** [comment]
For Hasura: https://hasura.io/docs/latest/graphql/core/deployment/postgres-requirements.html#postgres-permissions
