### ISSUE TITLE
CreateTimingPlaceForm loses focus when either input field is active

### ISSUE THREAD

**Issue by sr-vala** [HSLdevcom/jore4#1048]
Not very clearly visible in the image, but the 'Uusi Hastus-paikka' form becomes blurry when either input field is active.

![Image](https://user-images.githubusercontent.com/111305677/203918230-2f2daedc-f4dc-4e91-bbe3-f5a05f86aff6.png)

Needs research how to fix.

Note: tasaa tekstit.

**Comment by sr-vala** [comment]
Reproduced on Chrome 107 on macOS.

**Comment by HenrikHartiala** [comment]
This bug can be reproduced with at least the next setup:
**OS**: MacOs Monterey 12.6
**Browser**: Google Chrome Version 107.0.5304.110 (Official Build) (x86_64)
