### ISSUE TITLE
Create a document that lists automated tests per module

### ISSUE THREAD

**Issue by sr-vala** [HSLdevcom/jore4#1061]
List existing test cases in an Excel file to bring visibility to test automation coverage.

Use this excel as a base:

**Comment by HenrikHartiala** [comment]
The last manual testing document is in our drive, and we could extend it for other testing documentation purposes as well, like this one.

https://docs.google.com/spreadsheets/d/1xgi7MCWtuy2TtKqMK6ORmpDnLjiHOwL4q0aX8JFlnpI/edit#gid=0

**Comment by sr-vala** [comment]
Also adding a yarn library and script that lists all existing e2e tests.
