### ISSUE TITLE
Set up initial Tiamat project

### ISSUE THREAD

**Issue by culka** [HSLdevcom/jore4#1074]
Set up initial testing environment of Tiamat. This consists of;
- [x] Fork Tiamat
- [x] Update outdated library dependencies
- [x] Fix rutebanken.helper dependencies into a consistent version
- [x] Create docker image for Tiamat
- [x] Create postgresql docker image for Tiamat to use
- [x] Possibly update BIGINT ids to be UUIDs instead

Relates to #1668

**Comment by ellinooraikaheimo** [comment]
@culka what is the status in this ticket, is it blocked?

**Comment by ellinooraikaheimo** [comment]
@culka pls add checkbox to inform the work to be done in this ticket
