### ISSUE TITLE
Figure out/decide how to integrate Dependabot's PRs to our workflow

### ISSUE THREAD

**Issue by tk-vincit** [HSLdevcom/jore4#111]
- Test automerge in https://github.com/HSLdevcom/jore4-graphql-playground
  - re-subscribe also to dependabot pull requests in Slack to see the results
- Find suitable paths and config for https://github.com/HSLdevcom/jore4-flux and https://github.com/HSLdevcom/jore4-deploy

**Comment by haphut** [comment]
I enabled automerge (with only rebases allowed) for https://github.com/HSLdevcom/jore4-graphql-playground .

First speedbump: We require one reviewer for each PR so automerge is not enough to let Dependabot to merge its own PRs. The suggested solution ([#1](https://github.com/dependabot/feedback/issues/86#issuecomment-575933374), [#2](https://github.com/dependabot/feedback/issues/253#issuecomment-572618898)) is to use GitHub Actions to create an approval for Dependabot.
