### ISSUE TITLE
Create an offboarding documentation

### ISSUE THREAD

**Issue by ellinooraikaheimo** [HSLdevcom/jore4#1121]
In a similar manner as we have an onboarding documentation, we need to have offboarding documentation at Azure wiki. 

What to take into consideration once a team member is leaving?

Preliminary thoughts:
- Payment policy (no payments are tied to the person leaving)
- Passwords
- Access rights rotation (note: Juha-Matti can be contacted while PO transitioning throuh slack or e-mail)

PO will create a base, and team can make additions.

**Comment by culka** [comment]
Should this documentation be kept in the same open wiki or in a private one?

**Comment by ellinooraikaheimo** [comment]
Drive at the beginning?

**Comment by ellinooraikaheimo** [comment]
Further team member offboarding documentation will be further fullfilled in another ticket.
