### ISSUE TITLE
Document project's person related subscriptions / services

### ISSUE THREAD

**Issue by ellinooraikaheimo** [HSLdevcom/jore4#1122]
List project's payment subscriptions and go through with PO what is the desired state of these for the future.

Presumably these are handled through HSL, but needs to be double checked with Janeka

Note e.g. auto deploy api key

Create a slack thread to discover the situation and document to the selected place, relates to #1120

**Comment by eleksi** [comment]
Subscriptions are now documented in [wiki](https://dev.azure.com/hslfi/JORE%204.0/_wiki/wikis/JORE-4.0.wiki/1991/Project-subscriptions)
