### ISSUE TITLE
As planner I want see upper menu in map view

### ISSUE THREAD

**Issue by teittla** [HSLdevcom/jore4#1124]
Kartta- ja muihin avautuviin näkymiin yläpalkkiin valintapalkki kaikista toiminnoista, helpottaa siirtymistä

![Image](https://user-images.githubusercontent.com/105207476/214775242-86d9acb8-4ba2-485a-87b2-231833343654.png)

![Image](https://user-images.githubusercontent.com/105207476/214775601-8c027c0b-e48a-4740-ac5c-fe619f40a915.png)

**Comment by juhakolari** [comment]
Design considerations:
- conceptually, this is more about adding the map to the main navigation than vice versa
- initial/current concept: the map is a modal, with a well-defined start and end to the work done within the map
- proposed concept: the map is available in the main navigation as needed, with actions saved within it one at a time.

The initial design concept supported the idea of a combined saving of individual actions. This was not feasible technically, at least to the extent that it was planned. In addition to the early user feedback from the test version, having the map in the main navigation would perhaps be more in line with the current implementation as well. 

Some design iteration is needed to make sure the switch from a modal to a section in the main navigation goes smoothly. 
- make sure that the UI logic of saving works, including upcoming tagging, change history, naming and descriptions
- placement of possibly upcoming map search, version names and tags
- getting rid of the planned map header altogether in favour of the main navigation?
