### ISSUE TITLE
Create npm package of test-db-manager

### ISSUE THREAD

**Issue by pallost** [HSLdevcom/jore4#1142]
Currently the test-db-manager is only used in the UI repository for integration tests and cypress tests. It would however be very useful to have it as a shared library package to be reused also in hasura integration tests...

Maybe could use github pacakges registry for this.
Or another idea is just to reference the repository directly from hasura's package.json (but should think how this will be build in this case)

Discussed in a-rinki 16.2. but re-check what was the outcome.

**Comment by ellinooraikaheimo** [comment]
Will be taken into consideration among #1333
