### ISSUE TITLE
Decide how to transfer journey pattern snapshot information between JORE4 and Hastus

### ISSUE THREAD

**Issue by pallost** [HSLdevcom/jore4#1166]
Journey patterns are snapshotted so that we know that which version of the journey pattern the timetables were created for. Open questions:
- we need Hastus to pass some extra metadata to JORE to be able to identify that which journey pattern ref version the timetables were created for -> should consult with HSL that how this metadata could be passed, preferrably automatically
- should decide whether we create the journey_pattern_ref snapshot row when exporting routes or rather when importing timetables -> should decide with the team after learning how metadata could be passed between JORE and Hastus

**Comment by culka** [comment]
Created a follow up how this should be handled https://github.com/HSLdevcom/jore4/issues/1328
