### ISSUE TITLE
Add more loading spinners in UI

### ISSUE THREAD

**Issue by eleksi** [HSLdevcom/jore4#1167]
There are some operations that might take long and user should see loading indicator.

Design loaders for e.g. button click actions (show spinner in button, show spinner in corner or something like that).

For example when confirming route import confirm loader?

Discuss with design if necessary. [[Spinner for search in Figma](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/Timetables-%7C-Routes-and-lines-%7C-JORE-4.0-UX?type=design&node-id=2627%3A148920&mode=design&t=NB4J4zUo9meK2QGq-1).]

Places to add better user information about loading:
- [x] #1499
- [x] #1605
- [x] Add loading indicator to route export
- [x] opening line page (sometimes has a lot of content)
- [x] opening timetables page (same as above)

Relates to #1564

**Comment by HenrikHartiala** [comment]
Modified this ticket to have tasks and clarified the title and description. This is only a fraction of the loading spinners, but a good start.
