### ISSUE TITLE
Refactor route-related test data

### ISSUE THREAD

**Issue by sr-vala** [HSLdevcom/jore4#1169]
Make test inputs more visible in the test itself. FilterPanel page object needs to be moved into ModalMap page object.

**Comment by ellinooraikaheimo** [comment]
Why this has been moved out from the project? If not needed to be done, mark Close with comment and or delete completely. @sr-vala

**Comment by sr-vala** [comment]
> Why this has been moved out from the project? If not needed to be done, mark Close with comment and or delete completely. @sr-vala

I probably mean to delete this completely. Test file has changed so much already that the original purpose of this ticket became obsolete.
