### ISSUE TITLE
Fix digiroad shapefile download link

### ISSUE THREAD

**Issue by pallost** [HSLdevcom/jore4#1193]
The digiroad shapefile was moved to `https://ava.vaylapilvi.fi/ava/Tie/Digiroad/Aineistojulkaisut/latest/Maakuntajako_Digiroad_R/${AREA}.zip`. Also it seems that the datamodel might have changed, the importer does not work anymore.

**Comment by ellinooraikaheimo** [comment]
Discuss in refinement what is the need
