### ISSUE TITLE
Hastus export/import bug fixes

### ISSUE THREAD

**Issue by eleksi** [HSLdevcom/jore4#1218]
- [x] Fix bug where route's hidden variant is exported, when only base variant should be (in request "uniqueLabels": "65x", in response both "65x" and "65x 3" routes present)
- [x] Add variant information to exported routes without explicit variant. Route directions 1 and 2 should have variant 1 and 2 in export, even though variants are not defined in data model
- [x] Fix timing settings mapping order in rvpoint export. `is_used_as_timing_point` should be the third field instead of fifth
- [x] Fix `RouteIdAndVariantId` field in rvariant, it should also contain the variant even if there is no explicit variant defined. (1 and 2 for outbound and inbound directions)
- [x] Make rvpoint refer to a its route (rvariant) using `RouteIdAndVariantId`
- [x] Hastus importer does not take in to account `tstp_stop_id` and instead just assumes that the correct stops are in correct order. 
- [x] Dig out the type_of_line when creating journey_pattern_ref (It is required information for journey_pattern_ref)
- [x] Export hastus place / stop id are in the wrong order

More info about this in [this slack thread](https://vincit.slack.com/archives/C03UBME8C23/p1678961626430869).

Discuss with Teemu Mäkinen. :)

**Comment by HenrikHartiala** [comment]
`tstp_stop_id` issue example:

![Image](https://user-images.githubusercontent.com/82645403/226622469-bf24a3a4-58b7-4021-bd73-4709166d1277.png)

```
1;HASTUS;HSL;1.04;20230101;070707
2;23KEV;Kevät 2023;0065;05;20230101;20230630;CONTRACT
3;0065;05;02;HSL;20230101;20230630;20230101;070707
4;1234;65x - 1;1;1AACKT;1AURLA;65x; 3;  ;17
5;CONTRACT;1234;2345;1;0;65x;65x;;07:10;07:25; 28; 0; 3;2.400;0;;;1;17;0;0;0
6;2345;1AACKT;H1234;;;;;0810;0.0;T;
6;2345;1ELIMK;H1236;;;;;0818;808.0;T;

```

**Comment by eleksi** [comment]
![Image](https://user-images.githubusercontent.com/51695324/227178382-48e0ff0a-c7e0-4d5d-a620-1105ce694b8a.png)

Left is original, right is fixed
