### ISSUE TITLE
Via point names are broken in Jore3 Importer

### ISSUE THREAD

**Issue by jarkkoka** [HSLdevcom/jore4#1220]
Via point semantics is different between Jore3 and Jore4. In Jore3, a via point name is set (for a stop point) in advance, when the information is desired to become visible. In Jore4, a via point name is assigned to the stop point that is the actual via point.

Currently, Jore3 Importer assigns via points using the Jore3 scheme, which is incorrect and causes database constraint violations when importing and inserting `scheduled_stop_point_in_journey_pattern` instances to the Jore4 database.
- The information about whether a stop point is used as a via point is read from `viasuomi` field that has been deprecated and is no longer used in Jore3.
- Database constraints are caused by mismatches between `is_via_point` and via name fields. There are given via names for stop points that are not marked as via points, and vice versa

As a first step, we could disable assigning via points in export stage.

The actual via points can be deduced from when the via name changes in Jore3 to another or to null.

**Comment by HenrikHartiala** [comment]
If it turns out to be very complex and not viable solution to import the jore3 viapoint information in to jore4, we could also consider of manually typing in all the via points in to production.
