### ISSUE TITLE
run-cypress-tests action always tries to copy test results from '/cypress/reports'

### ISSUE THREAD

**Issue by sr-vala** [HSLdevcom/jore4#1227]
Test result copying step does not work when tests are run in other repositories than jore4-ui. The step tries to copy the results from the workspace, but the results should be copied from the cypress container.

`Warning: No files were found with the provided path: /home/runner/work/jore4-tools/cypress/reports. No artifacts will be uploaded.`

**Comment by ellinooraikaheimo** [comment]
Why this has been removed @sr-vala ?

**Comment by sr-vala** [comment]
> Why this has been removed @sr-vala ?

I don't think this is an issue after all.
