### ISSUE TITLE
Implement UI view for setting reference days

### ISSUE THREAD

**Issue by eleksi** [HSLdevcom/jore4#1229]
https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/Timetables-%7C-Routes-and-lines-%7C-JORE-4.0-UX?node-id=9376%3A327755&t=gAxCRyXPvIAOCFjH-1

"Satunnaiset poikkeuspäivät" is the default case for reference days. Other parts in this view are technically reference days as well, but they have some things defined in UI to help the user

**Comment by Perholehto** [comment]
- [ ] test1
- [ ] test2

**Comment by Perholehto** [comment]
Filter by line type not included in MVP

**Comment by Perholehto** [comment]
Hasura PR: https://github.com/HSLdevcom/jore4-hasura/pull/188
