### ISSUE TITLE
Update Kubernetes versions in Azure environments

### ISSUE THREAD

**Issue by jarkkoka** [HSLdevcom/jore4#1236]
There are unsupported Kubernetes versions in use in `dev` and `test` environments. These should be updated prior to e.g. creating Terraform IaC scripts.

Blocked by #957

**Comment by ellinooraikaheimo** [comment]
Pending Terraform experimentation (#1290)

**Comment by ellinooraikaheimo** [comment]
Moved and to be completed in Azure DevOps backlog
