### ISSUE TITLE
Switch to truncating the jore4e2e database in test cleanup

### ISSUE THREAD

**Issue by sr-vala** [HSLdevcom/jore4#1245]
Truncate database instead of deleting only the data that was created in the test. The current truncateDb function should be removed/refactored in this task also.

**Comment by sr-vala** [comment]
Not sure if this is a good idea. Deleting created test data works fine at the moment.

**Comment by ellinooraikaheimo** [comment]
@sr-vala is this closed? If so, please move to Done or delete from the backlog.
