### ISSUE TITLE
As a public transport planner I want to upload a schedule that runs a certain trip twice with two different vehicles

### ISSUE THREAD

**Issue by ossiberg** [HSLdevcom/jore4#126]
"Lähdön tuplaus". This is done in some cases when school is evacuated to a different position, and there are a lot of pupils to be transported and a capacity of one bus is not sufficient. Jore3 nowadays has issues with this.

If #427 and #426 are completed, this is completed as well.

--

Proposal for adding trip (instead of replacing) from Hastus and displaying doubled trips is commented in #427 . Otherwise a dev task if Hastus can handle this, but JORE3 does not?

**Comment by juhakolari** [comment]
Proposal for displaying doubled trips is commented in #427 . Otherwise a dev task?
