### ISSUE TITLE
As a public transport planner I want to upload schedules for a route that is run from two different contracts

### ISSUE THREAD

**Issue by ossiberg** [HSLdevcom/jore4#128]
Typically "overwriting" is a wise choice when uploading a timetables for a route for certain time range and priority. This is a case when it is required to keep the "old" timetables there, if the "old" ones are the recently uploaded ones from the another contract.

--

The [current Hastus import design](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=3238%3A256055) contains the option to combine imported timetables instead of replacing them.

**Comment by juhakolari** [comment]
The [current Hastus import design](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=3238%3A256055) contains the option to combine imported timetables instead of replacing them.
