### ISSUE TITLE
As a developer, I want to establish Azure DEV environment using HSL's ADO-Terraform pipeline

### ISSUE THREAD

**Issue by jarkkoka** [HSLdevcom/jore4#1290]
Initiate via Slack discussion. Sebastian Laaksonen has role in implementation.

More information in [wiki](https://dev.azure.com/hslfi/JORE%204.0/_wiki/wikis/JORE-4.0.wiki/2009/Architecture-meetings?anchor=11.5.2023-azure%2C-iac%2C-terraform)

Tasks:
- [x] Test connectivity to the jump box VM for private AKS cluster and get needed permissions
- [x] Test executing plan stage for Terraform pipelines in Azure DevOps
- [x] Test executing Terraform pipelines to the Azure resource group
- [x] Create Azure Virtual Network via Terraform to DEV environment 
- [x] #1703 
- [x] #1702 
- [ ] #1701  
- [x] #1683
- [ ] #1671 
- [ ] #1704 
- [ ] #1705
- [ ] ...

**Comment by jarkkoka** [comment]
Interesting links:
- https://learn.microsoft.com/en-us/azure/application-gateway/for-containers/overview

**Comment by ellinooraikaheimo** [comment]
Niki + Jarkko thinks about this and its priority
