### ISSUE TITLE
Add tests for changing vehicle schedule frame validity time

### ISSUE THREAD

**Issue by Leitsi** [HSLdevcom/jore4#1292]
https://github.com/HSLdevcom/jore4/issues/1156

Some cases that come to mind (might not be worth it to test all case):

Modal is opened from the change validity times button in line timetables view. Validity times can be modified and submitted.

Validity times in vehicle service table should be updated after successfully submitting modifications from the modal.

Should update UI after successful submit: line timetable not shown anymore if its validity time was modified to be outside current observation date.

When vehicle schedule frame has timetables for multiple routes: should show warning inside the modal about the validity time change affecting those routes.

Should block modifications and display an error (currently just a toast, see https://github.com/HSLdevcom/jore4/issues/1289 ) when modifications would cause conflicts, that is, when timetable would overlap with another vehicle schedule frame for same route.

![Image](https://user-images.githubusercontent.com/3958530/240577009-7513979b-ec7c-4a49-9e1e-163f45cbd702.png)

**Comment by sr-vala** [comment]
Exception cases will be handled separately in #1345
