### ISSUE TITLE
As a planner, I want to access a detailed list of the bus stop features from the bus stop infobox on the map

### ISSUE THREAD

**Issue by culka** [HSLdevcom/jore4#1301]
Switch over to bus stop features in the list view from the bus stop in the map view

As a public transportation planner, I want to access a detailed list of the bus stop features from the bus stop infobox on the map, in order to view and manage the stop's features

Flow
1. The user clicks on a bus stop, the infobox opens
2. The user clicks on the ID of the stop, indicated by the external link icon
3. The bus stop list view is opened in a new browser tab

- [x] #1666

https://www.figma.com/file/dsNMixsO1558hCX0XzRDrc/Bus-stops-%7C-JORE-4.0-UX?node-id=1190%3A63745&t=mBSIfwBWIVdulLsi-1

Blocked by #1304

**Comment by HenrikHartiala** [comment]
This has already been implemented
