### ISSUE TITLE
As a planner, I want to open a stop page where I can view basic properties of a stop

### ISSUE THREAD

**Issue by culka** [HSLdevcom/jore4#1304]
The stop view | Header and basic information

* Show minimal information of a stop (bus icon, stop label & name). This will be the base page for all the other editing cards.

Flow:
1. navigate to a stop
2. the highlighted properties are displayed at the top of the page as seen in Figma:

### Tasks

- [x] #1655
- [x] #1656
- [x] #1657

Note: Number of departures and boarding are not part of the MVP.

https://www.figma.com/file/dsNMixsO1558hCX0XzRDrc/Bus-stops-%7C-JORE-4.0-UX?node-id=743%3A47956&t=aPb33BhAjkcMaWeT-1

https://www.figma.com/file/dsNMixsO1558hCX0XzRDrc/Bus-stops-%7C-JORE-4.0-UX?node-id=1040%3A56391&t=LlcKsTedMVr98sf8-1

**Comment by HenrikHartiala** [comment]
We changed the title and description to be more precise. Changes can be seen above
It might be that we need to transfer the icon logic to another user story, since those properties needs to be created as Tiamat equipment properties.
