### ISSUE TITLE
As a planner, I want to view the basic information of a stop

### ISSUE THREAD

**Issue by culka** [HSLdevcom/jore4#1316]
The bus stop view | Basic information

As a planner, I want to view the basic information of a stop, in order to know and edit what content can be shared at which point.

Flow:
- navigate to a stop
(- navigate to basic information - not yet needed)
- view a card of properties:
  - Perustiedot
- The card switches to an editable view of the properties (in another user story)

![Image](https://github.com/HSLdevcom/jore4/assets/77675592/37fb94c0-16c9-4e66-a9d7-588fde24f13a)

- [x] #1679
- [x] #1681

https://www.figma.com/file/dsNMixsO1558hCX0XzRDrc/Bus-stops-%7C-JORE-4.0-UX?node-id=1062%3A57790&t=aPb33BhAjkcMaWeT-1

https://www.figma.com/file/dsNMixsO1558hCX0XzRDrc/Bus-stops-%7C-JORE-4.0-UX?type=design&node-id=1062%3A57970&t=RskQnW2PNYoCO4Hc-1

**Comment by Leitsi** [comment]
Moved and to be completed in Azure DevOps backlog.
