### ISSUE TITLE
Create a backend for timetables module

### ISSUE THREAD

**Issue by Leitsi** [HSLdevcom/jore4#1334]
We have encountered multiple cases where some complex functionality is difficult to implement with just SQL and GraphQL and frontend.
Problems include but not limited to:
- SQL functions in general are hard to maintain, debug and understand
- transaction handling when the functionality requires several steps: not always possible from UI and difficult in plain SQL

Adding such features would be easier with an actual backend where we could put these functionalities behind a REST / GraphQL API.

The scope of the backend should probably be limited to only timetables database.

Should probably be implemented with same technologies that we already use in other repositories.
Initial idea is to use Kotlin and Spring.

Things to note:
- endpoints should be transactional
- auth handling
- testing (see issue https://github.com/HSLdevcom/jore4/issues/1333)

**Comment by ellinooraikaheimo** [comment]
Add task list items, and split if necessary
