### ISSUE TITLE
Hasura transaction bug in Timetables DB

### ISSUE THREAD

**Issue by Perholehto** [HSLdevcom/jore4#1365]
Transactions doesn't work in Timetables database when request with multiple mutations is coming from UI.

More info: https://dev.azure.com/hslfi/JORE%204.0/_wiki/wikis/JORE-4.0.wiki/2523/Hasura-transaction-bug-in-Timetables-DB

**Comment by ellinooraikaheimo** [comment]
Discuss in a-rinki 2.8.

**Comment by culka** [comment]
Created follow up ticket of https://github.com/HSLdevcom/jore4/issues/1430
