### ISSUE TITLE
As a public transport planner I want to define rules what to import from external timetable source

### ISSUE THREAD

**Issue by ossiberg** [HSLdevcom/jore4#138]
Case U-lines and trains.

For example: "Remove all trains of route G" or "Import only trips that are on route 459"

--

[Proposal in Figma](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=3262%3A290712) for including or excluding selected routes. More focused filters can be included as needed.

**Comment by juhakolari** [comment]
[Proposal in Figma](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=3262%3A290712) for including or excluding selected routes. Additional filters can be added as needed.
