### ISSUE TITLE
As a planner I want to be able to set tariff zone to stops

### ISSUE THREAD

**Issue by culka** [HSLdevcom/jore4#1389]
It should be possible to add tariff zones to stops, as this is needed information for ticket systems which get their data from Jore4.

Design proposal: [Tariff zone is included in the stop register data (Figma).](https://www.figma.com/file/dsNMixsO1558hCX0XzRDrc/Bus-stops-%7C-JORE-4.0-UX?type=design&node-id=1118%3A61159&mode=design&t=XFU31jLoUBDAqmOX-1)

**Comment by ellinooraikaheimo** [comment]
Added to #1727
