### ISSUE TITLE
As a public transport planner I want to define school days for a route

### ISSUE THREAD

**Issue by ossiberg** [HSLdevcom/jore4#139]
In Jore3, there is no logic to figure out days that are not school days. In rural areas, large amount of trips are run only on school days. In jore4, we hope that there would be a possibility to use "+" and "x" notes that are used on Hastus and imported to Jore in order to figure out, whether a trip is run on a school vacation day or not.

In some specific use cases, (totally) different vehicle schedules are used for school days and school vacation days. This should not be prevented, either.

Hastus has a calendar feature that should be evaluated

--

[Global settings for school days and other periods that effect scheduling.](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=2861%3A243638) (Figma) Global settings include an option to set municipality and route-specific days.

[Settings accessed when examining a route](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=2956%3A207208) (Figma). It would seem useful to access route-specific school days also when already examining a route.

**Comment by juhakolari** [comment]
[Global settings for school days and other periods that effect scheduling.](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=2861%3A243638) (Figma) Global settings include an option to set municipality and route-specific days.

[Settings accessed when examining a route](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=2956%3A207208) (Figma). It would seem useful to access route-specific school days also when already examining a route.
