### ISSUE TITLE
As a developer I want to know how to integrate with hastus

### ISSUE THREAD

**Issue by eetuseta** [HSLdevcom/jore4#14]
As a developer I want to know is it possible to integrate to Hastus so that we have the features used there at my disposal.

If not possible, is there a way to combine multiple vehicle schedules to one export file Hastus -> Jore?

Check out valid questions regarding this and discuss in the architecture meetings

**Comment by haphut** [comment]
Add questions as comments:
- What kind of state does Hastus store?
  - If both Jore3 and Jore4 push data into Hastus, will we get conflicts? Do we need a separate Hastus instance for Jore4?
- What kind of APIs does Hastus offer?
- What data formats can Hastus import and export?

**Comment by jschummer** [comment]
What is the Hastus-jore3-CSV-format?

Is it actually CSV (different amount of columns in different rows)?

**Comment by jarkkoka** [comment]
What kind of route point and length information is conveyed from Jore to Hastus and vice versa?

- Are all route points part of data format? Or only stops?
- What length information is in the data format? (1) "jr_linkki" (measured or calculated from geometry of route path link), (2) "jr_pysakkivali" (from stop to another), (3) "jr_reitinsuunta" (total length of route into one direction)

**Comment by ossiberg** [comment]
Meeting was held and notes are available here: https://github.com/HSLdevcom/jore4/blob/main/wiki/hastus-integration.md
