### ISSUE TITLE
As a public transport planner I want Jore to understand to interpolate stop times, if some intermediate stop is missing from Hastus

### ISSUE THREAD

**Issue by ossiberg** [HSLdevcom/jore4#141]
Interpolating timetables -feature. Also useful when a new stop is created along a route, it would be very work-intensive to make new timetables in Hastus because of that.

--

[Hastus stops indicated in the line view](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=2861%3A228523) (Figma)

[Interpolation indicated in summary after saving? ](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=3036%3A208173)(Figma)

The level of detail for summary TBD. None/Number of stops/Change from previous routing (stops removed or added)

**Comment by juhakolari** [comment]
@ossiberg Are the requirements for design more or less as follows?

1) When a bus stop is moved, the user is _informed_ that the new stop time will be interpolated or the the interpolation needs to be _approved_ by the user.
2) The bus stops with interpolated stop times are indicated in the line timetables.
3) Any others?

**Comment by ossiberg** [comment]
@juhakolari 

1. When talking about moving a bus stop (this differs from the user story in title): If moving a Hastus stop, stop time should NOT be interpolated. MVP would be that moving stops would not trigger the interpolating feature, only when making a detour where new stops are added to the route. Answering to your question:  Neither is absolutely necessary, but informing the user is nice-to-have. 
2. Yes please :)
3. nope :)
