### ISSUE TITLE
As a public transport planner I want to get a notification when timetables on an external data source change.

### ISSUE THREAD

**Issue by ossiberg** [HSLdevcom/jore4#142]
For example when U-line has a change in its timetables, I want to be notified and check if the changes could be accepted to  be inserted into Jore4 database.

--

Design issues to consider:

To reduce notification glut, especially when e.g. transitioning between summer/winter schedules, should the notifications be targeted primarily based on line ownership?

We have a few design options according to how sticky or how prioritised the notifications need be.
**Option A) selected:** [Using the currently proposed alert](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=3279%3A290791) for saves and errors will be used for this purpose. 
B) If higher priority is needed, [a more prominent alert](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=3420%3A295878) below the header can be created.
C) The [existing list of highlighted timetables](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=3238%3A255394) on the main page does not quite capture the use case unless modified.

**Comment by juhakolari** [comment]
1) [Proposed alert](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=3279%3A290791) for saves and errors could be used for this purpose. 
2) If higher priority is needed, [a more prominent alert](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=3279%3A290766) below the header should be created.
3) The [existing list of highlighted timetables](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=3238%3A255394) on the main page does not quite capture the use case unless modified.
