### ISSUE TITLE
As a developer I want to have transactional substitute operaing period database operations

### ISSUE THREAD

**Issue by culka** [HSLdevcom/jore4#1430]
The current substitute operating period save logic is implemented as a graphql mutation which is not transactional, and will remove rows from the database if later of the three parts of it fail.

This logic should be moved to `jore4-timetables-api` in order to guarantee the integrity of the timetables database.

See reason here https://dev.azure.com/hslfi/JORE%204.0/_wiki/wikis/JORE-4.0.wiki/2523/Hasura-transaction-bug-in-Timetables-DB#

**Comment by ellinooraikaheimo** [comment]
Include to Timetables 1 if there is space. Otherwise include this to Test Realease milestone.

**Comment by culka** [comment]
Issue was fixed with a Hasura version update.
