### ISSUE TITLE
Research: When combining timetables, allow adding new vehicle journeys to existing blocks

### ISSUE THREAD

**Issue by Leitsi** [HSLdevcom/jore4#1431]
This seems to be an important case, as discussed with Selkisalo:
> Minun käsitykseni mukaan yhdistämisellä voidaan tuoda uusia lähtöjä olemassaoleviin autokiertoihin. Jos näin ei olisi, tulisivat uudet lähdöt siis aina uusille autokierroille. Jokaisesta yksittäisestä aikataulun/kaavion sisältämästä autokierrosta HSL joutuu maksamaan liikennöitsijälle "autopäivän" korvauksen (yleensä reilut 100 euroa), joten kustannusmielessäkin on järkevää, että uudet lähdöt tulevat mahdollisuuksien mukaan olemassaoleville autokierroille.

Currently we only move all vehicle_services from staging vehicle_schedule_frame to the target vehicle_schedule_frame.
Instead, a more deep merging should be performed.

To specify: how to determine which blocks should be merged.

Research and create implementatiotn tickets.

**Comment by ellinooraikaheimo** [comment]
Add to Timetables 1 module if there is time, otherwise to Test Release module.

**Comment by jarkkoka** [comment]
Needs more refinement from Selkisalo.

**Comment by ellinooraikaheimo** [comment]
A-rinki specification with Selkisalo.

**Comment by culka** [comment]
Created ticket for constraint, and documentation in wiki
https://github.com/HSLdevcom/jore4/issues/1482
