### ISSUE TITLE
Research: Prevent adding duplicate vehicle journeys when combining staging timetables

### ISSUE THREAD

**Issue by Leitsi** [HSLdevcom/jore4#1447]
In Jore3 this has been checked during the import process.
The imported (combined) timetable should not contain departures that already exist in the current timetable.
Vehicle journeys should be unique by: validity start time, day type, direction, route and departure time.

Currently our database constraints do not block this case.
Should either be checked in the /combine API, or at database level with constraints.

Current understanding is, that in Jore4:
- block times do not overlap within a vehicle service
- vehicle journey times do not lap within a block

Discuss in a-rinki 7.9. 

https://docs.google.com/spreadsheets/d/1JtklSwIm3CxqZrkquff4rHJoeA3q2_s_0npwkrDrM5s/edit?usp=sharing

**Comment by culka** [comment]
Documentation added to azure wiki.
