### ISSUE TITLE
Document how the combining logic works in Jore4

### ISSUE THREAD

**Issue by culka** [HSLdevcom/jore4#1482]
Document in wiki how the logic works. Note: technica documentation, so we remember later what this is about as a team.

How combining work in Jore3:

- In Jore3 combining timetables requires the start and end dates to match exactly in imported Hastus file and the existing one in database.
- No existing scheduled starts must exist in the database, only new ones can be added.
- Data is managed in route by route basis
- Vehicle journeys are identified by route id, start time (hour:minute), direction and day type.

Document how the Jore4 logic differs from Jore3.

Differences are at least:
- There can be simultaneous journeys for the same routes
- Data is not managed by routes, but by vehicle schedule frames
- Frames can contain multiple routes.

Related research ticket: https://github.com/HSLdevcom/jore4/issues/1431

**Comment by Leitsi** [comment]
https://dev.azure.com/hslfi/JORE%204.0/_wiki/wikis/4540e993-0bec-4793-be95-519d54ef8f33/3259/Import-timetables-by-combining#
