### ISSUE TITLE
Add loading indicator to search

### ISSUE THREAD

**Issue by juhakolari** [HSLdevcom/jore4#1499]
The view displays “0 hakutulosta”, and does not indicate an ongoing process. There should be a spinner and a text “Haku käynnissä”. A spinner has already been used in map mode. Also, when the search is completed, the advanced search could close to bring the results above the fold on smaller screens.

[Spinner for search in Figma](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/Timetables-%7C-Routes-and-lines-%7C-JORE-4.0-UX?type=design&node-id=2627%3A148920&mode=design&t=NB4J4zUo9meK2QGq-1
). 

Related to: #1167

**Comment by HenrikHartiala** [comment]
I'm not sure which spinner that is, or do we have that exact spinner currently anywhere? Currently we are using react-spinners for all the current spinners in jore4. We kind of need these loading indicators everywhere as soon as possible, so I will use the spinners we already have for now. It is really easy to change the spinner afterwards.
