### ISSUE TITLE
As a timetable planner, I want to reset substitute day settings due to changes information, in order to keep the settings up to date.

### ISSUE THREAD

**Issue by juhakolari** [HSLdevcom/jore4#1506]
When the user has set the services for a substitute day and saved the settings, the cross with which to reset the day disappears. The cross should be present also after saving.

![Image](https://github.com/HSLdevcom/jore4/assets/77674841/ec141672-2dd1-451a-839a-84c6f7f6e88a)

**Comment by HenrikHartiala** [comment]
Edited title and description from "special day" -> "substitute day"
