### ISSUE TITLE
Timetable file upload behaves unintuitively

### ISSUE THREAD

**Issue by niknii-vincit** [HSLdevcom/jore4#1548]
After choosing a timetable file to upload, one can not delete the already chosen file, except by browsing for a new file and canceling the process.

The same process also deletes previously chosen files, if one wants to add other files into the same upload, so all files need to be chosen in the same browse session.

[Design proposal in Figma for when the import view reflects the status in staging.](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/Timetables-%7C-Routes-and-lines-%7C-JORE-4.0-UX?type=design&node-id=12940%3A307645&mode=design&t=cBa9g11TMb1v1weW-1)

https://github.com/HSLdevcom/jore4/assets/135983800/5b281bc2-3a39-4b48-b32e-f46fe7357180

Proposed tasklist:

1. Add delete chosen file button
2. Research if the file can be kept when opening a new file browse event
3. Enable user to add a 2nd file afterwards

See also #1615 and combine if same thing

**Comment by niknii-vincit** [comment]
What do you think @ellinooraikaheimo, should this be kept in the backlog as a QoL update in the future, or close altogether?

**Comment by ellinooraikaheimo** [comment]
Closing seems like a valid option. We can discuss this tomorrow at the backlog refinement, @niknii-vincit you could present the case and we'll discuss the actions together

**Comment by ellinooraikaheimo** [comment]
Closed as not planned, this is not part of MVP, new ticket will be created by @juhakolari about the fix for after MVP development phase.
