### ISSUE TITLE
TEST & DEV environment "Show all" button returns 502

### ISSUE THREAD

**Issue by niknii-vincit** [HSLdevcom/jore4#1556]
>The button does indeed work in localhost, but it takes ~20s to fetch all ~2700 routes to be shown at once. In DEV and TEST environments checking network tab shows it returns 502: Bad Gateway. 
>
>This should either be improved by adding a loading indicator here while they load, or rethink does anyone really want to see all ~2700+ routes at once here? 🤔  (once the DEV & TEST environments work ofcouse)

_Originally posted by @niknii-vincit in https://github.com/HSLdevcom/jore4/issues/1498#issuecomment-1768394520_

**Comment by Perholehto** [comment]
![Image](https://github.com/HSLdevcom/jore4/assets/129253498/1e30d0a9-5189-4d2b-957c-70d3100b6c55)

Result contains same route many times, different validity period. All links with same route label are to the same page. 
Maybe we could fetch single row for each route.
