### ISSUE TITLE
Display a warning in UI if user is about to combine existing journeys in timetable import

### ISSUE THREAD

**Issue by Leitsi** [HSLdevcom/jore4#1566]
As it has been working in Jore3. See https://github.com/HSLdevcom/jore4/issues/1482 :
> How combining work in Jore3:
>    No existing scheduled starts must exist in the database, only new ones can be added.

Selkisalo on this check:
> Jore3:n sisäänluku tarkistaa, ..., että Hastuksesta nyt tuotavassa aineistossa ei ole lähtöjä, jotka jo aiemmin löytyvät samaan aikaan voimassaolevan aikataulun lähdöistä.
and also:
> lähdön avaintiedothan ovat reittitunnus, aikataulun voimaanastumispäivä, päivätyyppi, suunta, lähtöaika

Related to https://github.com/HSLdevcom/jore4/issues/1483
This issue was meant to address this existing journeys case, but doesn't actually help. When combining timetables we currently add new `vehicle_journeys` only as completely new `vehicle_services`, and the constraint implemented in #1483 only checks integrity within a single `vehicle_service`.

Needs specification, how should this exactly be handled. What is the requirement specifically? Current constraint limits overlapping journeys inside a service, but this would mean preventing adding identical journeys inside a frame, regardless of service.

Some possible options on implementation:
- check only when combining timetables, against the target vehicle schedule frame
- implement as a DB constraint
  - should this be by vehicle_schedule_frame or by priority? (probably by frame is enough, see `overlapping_schedules` constraint)

Also needs specification on how the `is_extra_journey` and `is_backup_journey` flags in `vehicle_journey` affect this.
- apparenty (one of?) these have been used in Hastus to implement same minute departures

Probably this does not need to be checked when replacing timetables, since a Hastus-file can only have a single day type = a single vehicle service, and within a vehicle service there can be no overlapping journeys.

Might need input from user testing for specifying this.

Meeting: Tommi, Teemu, Jarkko

Get files from Jenö.

Open questions (EDIT: see the answer in the comment):
- are contract numbers related to this?
  - eg. do we allow same minute departures for a route as long as they are from different contract?
- how are `is_extra_journey` trips handled? Are they exempt from this constraint?
- how are `is_backup_journey` trips handled? Are they exempt from this constraint?
- is this enough to avoid "*duplicate journeys must be separated by one minute*" workarounds?

**Comment by ellinooraikaheimo** [comment]
Discuss 24.11. in business weekly

**Comment by Leitsi** [comment]
Initial design idea for showing these warnings in the UI, similar to _poikkeamat_: https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/Timetables-%7C-Routes-and-lines-%7C-JORE-4.0-UX?type=design&node-id=12833%3A62612&mode=design&t=Qpx1nAB9pPPGj9Dy-1

**Comment by ellinooraikaheimo** [comment]
@Leitsi , @culka  + @juhakolari  discuss and create a new ticket how this should be done

**Comment by Leitsi** [comment]
Implement this first without contract number logic, add that once possible. https://github.com/HSLdevcom/jore4/issues/1636
