### ISSUE TITLE
As a timetable planner, I want the route export file name to contain the ID of the exported route, in order to identify them when selecting the file to import to Hastus.

### ISSUE THREAD

**Issue by juhakolari** [HSLdevcom/jore4#1576]
The filename should contain at least the route name and (perhaps) priority “35_Perusversio_2023-10-25”

Purkkafix minimitoteutus, ekan linjan tunnus alkuun.

**Comment by jarkkoka** [comment]
What about the case when multiple routes are exported using wildcard search criteria like "3*"?
