### ISSUE TITLE
As a timetable planner, I want to view the timetable on the versions page in detail, in order to check that the timetables are in order.

### ISSUE THREAD

**Issue by juhakolari** [HSLdevcom/jore4#1577]
Add the action “Näytä aikataulun tiedot” under the three dots. [[Figma](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/Timetables-%7C-Routes-and-lines-%7C-JORE-4.0-UX?type=design&node-id=3238%3A257062&mode=design&t=GmpT0KXsItv2eUsH-1)]

[Displaying the timetable (Figma)](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/Timetables-%7C-Routes-and-lines-%7C-JORE-4.0-UX?type=design&node-id=13102%3A155713&mode=design&t=dJ5NIWgTyHAwyouS-1).

The timetable modal can also be opened by clicking on the day type cell in the table. When the modal is open and a different day type cell is clicked, the new content replaces the previous timetable without a need to close it separately.

--

Usability note: The clickable area would be more easy to identify if there was a mouseover for the day type cell as well as the hand cursor. e.g. 50% transparency for the cell background when hovering.

Accessibility note: Check that the clickable cell can be accessed and a focus frame is displayed also when navigating with a keyboard.

**Comment by HenrikHartiala** [comment]
If we want this to also work with the drafts, we probably need changes on the details page as well. Can't remember precisely, but just a heads up, that this might also be an M-size ticket.

**Comment by HenrikHartiala** [comment]
Regarding my earlier comment, that comment is now outdated because we changed the specification. This new feature of checking the timetables of versions should work just as good for drafts as well.
