### ISSUE TITLE
Display better errors when saving timetables import fails because of DB constraints

### ISSUE THREAD

**Issue by Leitsi** [HSLdevcom/jore4#1584]
Currently only displayed as `JDBC commit failed` on frontend.

- [x] Needs first changes to the `jore4-timetables-api` backend
- [x] View error messages in frontend

An MVP for this would be to throw the DB error message as well, maybe wrapped in a custom "commit failed" exception class.

**Comment by jarkkoka** [comment]
Tommi could make a proposal about error message format regardin `jore4-timetables-api`.
