### ISSUE TITLE
Fix a bug in producing the 2nd field in `rvariant` row to Hastus export

### ISSUE THREAD

**Issue by jarkkoka** [HSLdevcom/jore4#1591]
The bug report in Finnish:

> Toinen asia, josta on jo puhuttu täällä, ettei reittien Hastus-siirto mene läpi, kun siirrossa on enempää, kuin linjan kaksi perusreittiä (siis 1 ja 2). Syy on varmaan siinä, että Jore4:n generoimassa siirtotiedostossa "rvariant" riveissä sarakkeen "B" (var_identifier) arvo on väärin. Tiedostossa on aina "1" tai "2", mutta tämä on oikein vain perusreittien tapauksessa. Kirjainvarianteilla pitäisi olla siinä myös kirjainten. Siis esim. 348BK reiteillä BK1 ja BK2, 348K reiteillä K1 ja K2. Niin sanotuilla "välilyöntivarianteilla", esim. "348K 3", välilyönti pois, siis K31 ja K32. Nämä kaikki puuttuvat nykyään siitä siirtoExcelistä, näin Hastus lukee kyllä sisään variantit 1 ja 2, mutta kun löytyy seuraava varianti "1", siirto tuottaa virheilmoitusta ja Hastukseen ei muodostu uusi linja. Tämä asia korjattava mahd. pian, koska ilman reittien siirtoa on vaikea jatkaa testausta.
> Tässä esimerkkinä kuva Jore3:n siirtotiedostosta, jossa var_identifier on oikein

The estimated work effort is 1-2 days including possible refactoring and JUnit tests.

**Comment by jarkkoka** [comment]
Here is a sample of correct processing of `rvariant`.

![Image](https://github.com/HSLdevcom/jore4/assets/1404781/90e31060-7fa2-4128-a1d6-cb862f0a291c)

**Comment by ellinooraikaheimo** [comment]
Inform Jenö once the bug has been fixed, in the projects slack channel.
