### ISSUE TITLE
Cannot access Azure Kubernetes and bastion host outside Vincit office

### ISSUE THREAD

**Issue by jarkkoka** [HSLdevcom/jore4#1603]
The Vincit VPN exit node whose IP address has been added to trusted IP addresses can not be used anymore. The IP addresses of the VPN must be changed to the currently used exit nodes.

Access restrictions affect Jore4 bastion hosts and AKS service (in all Azure resource groups). These services need to updated for the trusted IP addresses.

The needed actions are:
- [x] #1640 
- [x] #1641 
- [x] #1642

**Comment by ellinooraikaheimo** [comment]
Solve with VIncit IT asap

**Comment by jarkkoka** [comment]
We need to change the Vincit VPN address.

**Comment by jarkkoka** [comment]
Some useful links:

- https://learn.microsoft.com/en-us/azure/aks/api-server-authorized-ip-ranges
