### ISSUE TITLE
Fix route description in `jore3-importer` logic

### ISSUE THREAD

**Issue by jarkkoka** [HSLdevcom/jore4#1604]
Currently, the value of the multilingual `route.route.description` field is mapped from the `jr_reitti.reinimi` and `jr_reitti.reinimir` fields of Jore3. The route description is included in the Hastus export.

However, it seems that the `jr_reitinsuunta.suunimi` and `jr_reitinsuunta.suunimir` fields should be used instead as source for the `description_i18n` field of the Jore4 route, as those fields have different values for each direction.

**Comment by ellinooraikaheimo** [comment]
Only possible to make at the moment at the office

**Comment by jarkkoka** [comment]
There is no VPN problem anymore.
