### ISSUE TITLE
Show warning when combining timetables for the same contract and with the same validity period

### ISSUE THREAD

**Issue by jarkkoka** [HSLdevcom/jore4#1609]
The timetables combining feature is meant to be used with different contracts.

Design proposal: 
Add warning when overlapping contract numbers are to be combined when the user selects the "Yhdistä tiedot" option either in preview or the save modal in the import view.
[Warning in import preview (Figma)](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/Timetables-%7C-Routes-and-lines-%7C-JORE-4.0-UX?type=design&node-id=13059%3A150940&mode=design&t=Sq1WLQta94A8SIED-1)
[Warning in save modal (Figma)](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/Timetables-%7C-Routes-and-lines-%7C-JORE-4.0-UX?type=design&node-id=13059%3A150743&mode=design&t=Sq1WLQta94A8SIED-1).

Example:
![Image](https://github.com/HSLdevcom/jore4/assets/77674841/16c2d70e-4708-47d7-b54a-c895d53d3fd1)

**Comment by juhakolari** [comment]
Split the description into a separate ticket. Design needed for both.
