### ISSUE TITLE
As a Developer I want to have access to Azure's services from office's network (without VPN)

### ISSUE THREAD

**Issue by tk-vincit** [HSLdevcom/jore4#161]
Should go somehow like this:
- Add new ip to env-test.yaml
- run `playtest play-provision-rg-and-nets.yaml` (or something like that) in ansible

**Comment by jschummer** [comment]
The process changed somewhat, nowadays it's enough to add your IP to the whitelist (NSG) via Azure portal. The step is described in the [onboarding guide](https://github.com/HSLdevcom/jore4/blob/main/wiki/onboarding.md#adding-your-ip-to-the-whitelist-nsg).
