### ISSUE TITLE
As a user I shoudn't see items in the preview area that are already cancelled

### ISSUE THREAD

**Issue by AlJelo005** [HSLdevcom/jore4#1614]
From the user evaluation (PRORITY 1): **Hastus import - Drag & drop:** 

Files were loaded onto the drag and drop area. The process was cancelled, but the files still appeared in the drag and drop area.

[Timetables - Evaluation results | Map](https://docs.google.com/spreadsheets/d/119qdTkm2OZs85iRiIqE1q1LY4eMGuYAQNtqqml8OKI8/edit#gid=0)

**Comment by HenrikHartiala** [comment]
This is the correct MVP behaviour and the issue was due to misunderstanding of the MVP implementation. So this ticket can be closed.
