### ISSUE TITLE
As a user I want to be able to replace a timetable

### ISSUE THREAD

**Issue by AlJelo005** [HSLdevcom/jore4#1616]
From the user evaluation (PRORITY 1): 

Importing a replacement timetable with the exact same validity period does not replace or function in any way. No error message, the button appears to do nothing.

Ask Tommi?

[Timetables - Evaluation results | Map](https://docs.google.com/spreadsheets/d/119qdTkm2OZs85iRiIqE1q1LY4eMGuYAQNtqqml8OKI8/edit#gid=0)

**Comment by ellinooraikaheimo** [comment]
Specify ideal way and create a ticket if necessary

**Comment by juhakolari** [comment]
Cannot be reproduced.
