### ISSUE TITLE
As a user I want to see all of the departure times in the correct order

### ISSUE THREAD

**Issue by AlJelo005** [HSLdevcom/jore4#1617]
From the user evaluation (PRORITY 1): 

**Stop view: Last timetables are in wrong order.**

Some of the departures from the final stop on the route are in the wrong order, e.g. 12 58 03 11. (It seems that this issue appears for the last, evening timetables only?)

![Image](https://github.com/HSLdevcom/jore4/assets/146091050/5839ffeb-b438-42f5-b377-055688adecc3)

[Timetables - Evaluation results](https://docs.google.com/spreadsheets/d/119qdTkm2OZs85iRiIqE1q1LY4eMGuYAQNtqqml8OKI8/edit#gid=0) | Map (row 75)

Research if duplicate with #1547

**Comment by HenrikHartiala** [comment]
A ticket was made to add data to e2e tests to catch this in the future. [#1635](https://github.com/HSLdevcom/jore4/issues/1635)
