### ISSUE TITLE
As a transport planner I want to know what stop areas or stops are part of a terminal

### ISSUE THREAD

**Issue by ossiberg** [HSLdevcom/jore4#162]
As a list on UI, exportable to csv

**Comment by juhakolari** [comment]
Design considerations

- Bus stop registry information: The bus stop's [parent bus stop area](https://www.figma.com/file/dsNMixsO1558hCX0XzRDrc/Bus-stops?node-id=733%3A35259&t=vZ7e94jsLhTUEp0J-1) (Figma) and [terminal](https://www.figma.com/file/dsNMixsO1558hCX0XzRDrc/Bus-stops?node-id=733%3A36856&t=vZ7e94jsLhTUEp0J-1) (Figma) will be displayed and editable
- Under terminal: When listing the terminal's bus stops in a separate view, the stops can be [grouped according to the bus stop area](https://www.figma.com/file/dsNMixsO1558hCX0XzRDrc/Bus-stops?node-id=733%3A34609&t=vZ7e94jsLhTUEp0J-1) (Figma)
- Announcements: Considering the bus stop area's essential role in linking the correct announcements to groups of bus stops, the concept will be iterated once announcements are worked on.
- Export to CSV TBD
