### ISSUE TITLE
As a timetable planner, I want to see all routes open by default in the day type view, to avoid clicking each time I check the departure times

### ISSUE THREAD

**Issue by juhakolari** [HSLdevcom/jore4#1628]
User evaluation comment (PRIORITY 1): Displaying all routes and directions on an observation date should be the default setting.

[Timetables - Evaluation results | Timetables](https://docs.google.com/spreadsheets/d/119qdTkm2OZs85iRiIqE1q1LY4eMGuYAQNtqqml8OKI8/edit?usp=sharing)

**Comment by juhakolari** [comment]
Add also indication whether there are timetables or not.

**Comment by HenrikHartiala** [comment]
No need to add another indication, there is already "No timetables" if the row is expanded. Now if we expand all by default, the user can see if the route has timetables or not. If we want to show some indication on the row while it is not expanded, we would need a design for that. But I think that is not needed.
