### ISSUE TITLE
As a public transport planner I want to see a changelog of all changes to Jore that could be filtered

### ISSUE THREAD

**Issue by ossiberg** [HSLdevcom/jore4#165]
Filtering at least by the following criterion:
- User
- Date range of modification
- Date range of the change itself
- Route
- Stop
- Terminal

This is probably something that includes tickets like jore4#164

My first gut feeling is something like Wikipedia's similar tool: https://en.wikipedia.org/wiki/Special:RecentChanges

**Comment by juhakolari** [comment]
Change log should be available also when making changes in e.g. map mode. It can be made available as a sheet on the right hand side of the map by clicking on an icon.
