### ISSUE TITLE
Populate Azure Key Vault via Terraform to DEV environment

### ISSUE THREAD

**Issue by niknii-vincit** [HSLdevcom/jore4#1683]
We have generated passwords when the infrastructure is created with Ansible, so we need to convert the same functionality with Terraform. 

- [x] Create generation code configuration
- [x] Create Key Vault configuration
- [x] Test it with `plan`
- [x] Fix checkov errors
- [x] Review with @jarkkoka 
- [ ] Implement PR suggestions
- [ ] Add missing credentials
- [ ] Figure out way to generate secrets into Key Vault
- [ ] Apply it

**Comment by niknii-vincit** [comment]
On hold currently, can't access Checkov errors, which is stuck in HSL's support([ticket](https://dev.azure.com/hslfi/Azure-automation/_workitems/edit/32637)).

**Comment by ellinooraikaheimo** [comment]
Closed as not planned. This is not secure choice enough.
