### ISSUE TITLE
As a planner I want to edit the basic information of a stop

### ISSUE THREAD

**Issue by ellinooraikaheimo** [HSLdevcom/jore4#1707]
As a planner, I can select Edit (Muokkaa) and edit mode of a basic information card opens. User can make edits.

- Save button is deactivated until changes are made
- Edit any of the properties
~- Set the validity period for the changes~
~- Set the priority (use the new priority radio buttons) for the changes~
- Save 
- The card returns to the read mode
- a success/fail-toaster is displayed
~- The observation date is moved to the first day of the validity date of the changes~

~Note: Always a new version is created after the edits are in Pysäkkitiedot or Sijainti card.~

![Image](https://github.com/HSLdevcom/jore4/assets/77675592/fc21f996-54de-44b5-ae69-915ec4481405)

- [x] #1708
- [x] #1680 
- [x] #1724
- [x] #1681

**Comment by HenrikHartiala** [comment]
Edited the user story to not include any priority or validity changes
