### ISSUE TITLE
Specify the logic of Save

### ISSUE THREAD

**Issue by ellinooraikaheimo** [HSLdevcom/jore4#1708]
What happens when the stop is saved. When the new version created and where?

Discuss:
- First chance is to create versions - do we want to do this?
- Check few scenarios 

This is technical specification, meaning that involve Jore4 dev team. Add Juha-Matti as optional.

**Comment by HenrikHartiala** [comment]
Talked about this in a meeting and we decided that we always modify the version that is being modified. We do not create new version of the stop every time some details are changed. This explicit way of editing is much easier to understand. So if the user wants that some details are in effect for a particular period of time, he/she creates a new version of the stop and then modifies as he/she wishes.
