### ISSUE TITLE
As a planner I want to view location information of a stop

### ISSUE THREAD

**Issue by ellinooraikaheimo** [HSLdevcom/jore4#1709]
The bus stop view | Basic information

As a planner, I want to view the location of a stop, in order to know and edit what content can be shared at which point.

Flow:
- navigate to a stop
(- navigate to basic information - not yet needed)
- view a card of properties:
  - Sijainti
  - Pysäkin osoite, postinumero, ~kunta~, ~maksuvyöhyke~, leveysaste, pituusaste, korkeus and toiminnallinen alue.
Pysäkkialue and Terminaali -parts are part of another user story.
  - Kunta: blocked by  #1728
  - Maksuvyöhyke: blocked by #1727
- User can use expandable header 

![Image](https://github.com/HSLdevcom/jore4/assets/77675592/723903e1-6df1-49b7-afcb-79b6650d94f3)

https://www.figma.com/file/dsNMixsO1558hCX0XzRDrc/Bus-stops-%7C-JORE-4.0-UX?type=design&node-id=1062%3A57970&t=RskQnW2PNYoCO4Hc-1

Tasks:
- [x] #1713

**Comment by Leitsi** [comment]
Moved and to be completed in Azure DevOps backlog.
