### ISSUE TITLE
As planner I want to edit a location of a bus stop

### ISSUE THREAD

**Issue by ellinooraikaheimo** [HSLdevcom/jore4#1710]
As a planner, I can select Edit (Muokkaa) and edit mode of a location card opens. User can make edits.

- Save button is deactivated until changes are made
- Edit any of the properties
- Set the validity period for the changes
- Set the priority (use the new priority radio buttons) for the changes
- Save 
- The card returns to the read mode
- a success/fail-toaster is displayed
- The observation date is moved to the first day of the validity date of the changes

Note: Always a new version is created after the edits are in Pysäkkitiedot or Sijainti card. 

Note: Pysäkkialue and terminaali are not part of this.

![image](https://github.com/HSLdevcom/jore4/assets/6605534/58ab6f85-03fa-4517-8677-52aca5c1e690)

- [x] #1714
- [x] #1715

**Comment by Leitsi** [comment]
Moved and to be completed in Azure DevOps backlog.
