### ISSUE TITLE
Edit stop location UI

### ISSUE THREAD

**Issue by culka** [HSLdevcom/jore4#1714]
Add fields to edit the basic information as they are in figma.

Hide the header map, edit and fold -buttons when in edit mode.

- view a card of properties:
  - Sijainti
  - Press "Muokkaa"
- The card switches to an editable view of the properties
- Save button is deactivated until changes are made
- Edit any of the properties
- Set the validity period for the changes
- Save
- The card returns to the read mode
- a success/fail-toaster is displayed
- The observation date is moved to the first day of the validity date of the changes

Tasks:
- [ ] UI for editing the properties
- [ ] Edited properties save their values
- [ ] Update the validity period and priority for the stop in lines and routes database

Data model: https://dev.azure.com/hslfi/JORE%204.0/_wiki/wikis/JORE-4.0.wiki/3561/Stop-location#

Figma: https://www.figma.com/file/dsNMixsO1558hCX0XzRDrc/Bus-stops-%7C-JORE-4.0-UX?type=design&node-id=1118-61150&mode=design&t=vyCitBn4X4lKJK7V-4

**Comment by Leitsi** [comment]
Moved and to be completed in Azure DevOps backlog.
