### ISSUE TITLE
Edit signage

### ISSUE THREAD

**Issue by ellinooraikaheimo** [HSLdevcom/jore4#1718]
The bus stop view | Basic information

As a planner, I want to edit the signage of a stop, in order to inspect if they are up to date with current and upcoming changes in e.g. bus stop names.

Flow:

navigate to a stop
(- navigate to basic information - not yet needed)
Edit a card of properties:
Pysäkkikilvet

(Ask Juha for design if needed)

Pysäkkikilpien tyyppien vaihtoehdot:
ei kilpiä, ,linjaton kilvitys, lähibussikilvitys, linjojen merkintä

Note: Raideliikennettä korvaava and Runkolinjapysäkki are also bus stop properties, but they should be considered as requirements for signage. As signage properties they indicate, if they have been implemented in signage.

**Comment by Leitsi** [comment]
Moved and to be completed in Azure DevOps backlog.
