### ISSUE TITLE
Add priority and validity changes to edit stop

### ISSUE THREAD

**Issue by HenrikHartiala** [HSLdevcom/jore4#1724]
Add priority and validity period changes to stop place editing.

Note: These changes requires the same validation checks that are done when creating a new version of a stop or editing an existing version of a stop in map mode. 

- [ ] Update the validity period and priority for the stop in lines and routes database

**Comment by HenrikHartiala** [comment]
Hmm, after we decided that we are not going to always create new versions of the stop when saving, and we rather just modify the entity directly, this raises two questions. **First** is that should we even have this priority / validity edit in the basic information card? **Second** is that if **we do** want it here, should we also show the priority and validity in the basic information view card?

**Comment by ellinooraikaheimo** [comment]
No need to implement.
