### ISSUE TITLE
As a information planner I want to make an installation instruction for stop signs

### ISSUE THREAD

**Issue by ossiberg** [HSLdevcom/jore4#185]
"Kilvitysohje"

Specify with Joona Packalen

**Comment by juhakolari** [comment]
[Placement of action in Figma](https://www.figma.com/file/dsNMixsO1558hCX0XzRDrc/Bus-stops-%7C-JORE-4.0-UX?type=design&node-id=931%3A49989&t=YpTaINsx6NubuLns-1). Will come upo in Miro user story map.
