### ISSUE TITLE
As a business owner I want to make a plan of a work process how book timetables should be done in Jore4

### ISSUE THREAD

**Issue by ossiberg** [HSLdevcom/jore4#195]
EDIT 3/2022: Please ask Joona Packalén if this is feasible feature at all before doing anything else

Current issues in Finnish:

Joukkoliikennesuunnittelijana   haluan tuottaa kirja-aikataulun linjalle. | Kirja-aikataulu tuotetaan voimassaoloajalle uusien aikataulujen   latauksen jälkeen linjakohtaisesti.
-- | --
Joukkoliikennesuunnittelijana   haluan tuottaa yhden kirja-aikataulun koko aikataulukaudelle linjalle, jolla   on +-sekä x-lähtöjä ja/tai ma-to aikataulut eroavat toisistaan. | Tällä hetkellä kyseisissä tapauksissa täytyy ladata koko   aikataulukaudelle kaikki aikataulut, siten että ne ovat voimassa joka päivä,   ja tuottaa TAKU-aikataulu. Tämän jälkeen tuoda uudestaan aikataulut   pilkottuna kouluaikatauluihin (x) ja koulujen loma-aikatauluihin (+).

**Comment by ellinooraikaheimo** [comment]
Closed, no need to do at this moment since there is no vision about the Taku's roadmap.
