### ISSUE TITLE
As a planning assistant I want to create or modify a stop

### ISSUE THREAD

**Issue by ossiberg** [HSLdevcom/jore4#212]
[Bus stop information in map mode (Figma)](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=1165%3A331)

[Bus stop information in list mode (DRAFT, Figma)](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=1251%3A0)

**Comment by haphut** [comment]
Comment from Ossi in backlog refinement 2021-03-25: Here stop is just a point along a route.
