### ISSUE TITLE
Import Jore3 routes to Jore4 using map matching service

### ISSUE THREAD

**Issue by haphut** [HSLdevcom/jore4#221]
Jore3 is the source of route data for Jore4.

Dependency #267 

**Tasks (or possible new tickets):**

- [x] Import routes to the Jore 4 database.
- [x] Import journey patterns and scheduled stop points to the Jore4 Database

**Comment by haphut** [comment]
Aspects for reducing scope of the first iteration:
- import minimal info about stops
- import minimal info about routes except for route geometries and journey patterns
- bring only bus routes
  - onto unconflated Digiroad
- skip map matching
  - requires DDL for freeform route geometry, to be removed after map matching

**Comment by lassemaatta** [comment]
Only fetch the data; do not e.g. attempt map matching.

**Comment by jarkkoka** [comment]
Scope update proposal:
- Jore3 importer needs to invoke REST API of map matching backend to match Jore3 routes against Digiroad network
- Map matching backend will resolve an ordered list of infrastructure links (Digiroad `link_id`)
- Jore3 importer transfers route into appropriate Jore4 schema of Hasura database
