### ISSUE TITLE
As a public transport planner I want a clear visualization of what happens on a certain day

### ISSUE THREAD

**Issue by ossiberg** [HSLdevcom/jore4#236]
Such as "On 23th of December 2021: Stop E2103 gets a new name, route 665 gets new timetables and stop H1234 is relocated"

[Proposal of textual summary (Figma, right column)](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=1519%3A48339)

[Proposal of timeline visualisation on the versions page (Figma)](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=1711%3A62536)

**Comment by juhakolari** [comment]
The title indicates a visualisation. However, using titles and description for changes, a textual summary may be even better.
