### ISSUE TITLE
As a communication planner I want to be able to define  announcements to take place when arriving to a bus stop from either directions.

### ISSUE THREAD

**Issue by ellinooraikaheimo** [HSLdevcom/jore4#244]
Previously the announcements are linked to a bus stop area; and this causes issues when announcing about e.g. worksites that only affect single bus stop. LIJ limits this case, yet it should be covered in new Jore. Pubtrans might support only areas. 

[Kehitysideat_1.käyttäjäpalautekierros](https://docs.google.com/spreadsheets/d/1M1P3EUg3HbDb4aH-C2pa1FZmskTty_WS1fcRDrHLqRw/edit#gid=0)

**Comment by juhakolari** [comment]
Route directions not likely to be viable for this purpose.
