### ISSUE TITLE
As a person responsible on infrastructure, i want to be able to see information on charging stations in Jore.

### ISSUE THREAD

**Issue by ellinooraikaheimo** [HSLdevcom/jore4#245]
Requires further planning, whether this info is shown in the bus stop, terminal etc. level. What is the correct hierarchial place to show this? Case: pikapysäköintipaikkojen laturit  

[Kehitysideat_1.käyttäjäpalautekierros](https://docs.google.com/spreadsheets/d/1M1P3EUg3HbDb4aH-C2pa1FZmskTty_WS1fcRDrHLqRw/edit#gid=0)

**Comment by ossiberg** [comment]
Information will include but is not limited to location (coordinates), properties of the charger as well as electricity connection. There is also a need of storing and reporting information about contract, such as contractor name and validity period.

**Comment by juhakolari** [comment]
Taken into account in user story map in Miro.
