### ISSUE TITLE
Saavutettavuuden automaattinen testaus - AA(wcag2.1)

### ISSUE THREAD

**Issue by eetuseta** [HSLdevcom/jore4#25]
As a developer I want to have automated tests regarding accessibility so that my features are compatible with the standards.

Research how to take into consideration. (Plan when to add DoD, how to proceed with this etc.)

Document plan

**Comment by jpeuralinna** [comment]
Tools that could be used to automate accessiblity testing:
 Google Lighthouse:
- Open-source
- Has an existing Github app, so it could be added to our ci checks in ui repo.
- Tests aren't as comprehensive as some other tools like axe or siteimprove.

Siteimprove 
- paid service
- Has some kind of api that could propably be used for integrating tests in our CI/CD pipelines.
- Used by many companies in Finland.

Tenon.io
- Requires paid subscription for automating the tests.

axe DevTools
- Requires Enterprise subscription for CI/CD integration features.
- Google Lighthouse is built on top of axe, but axe has more tests than lighthouse

Most of these tools also provide scans that can be performed manually for web pages.
