### ISSUE TITLE
As a public transport planner I want to keep a registry of planned changes from route to another

### ISSUE THREAD

**Issue by ossiberg** [HSLdevcom/jore4#255]
GTFS's Transfers.txt file https://developers.google.com/transit/gtfs/reference#transferstxt

**Comment by juhakolari** [comment]
Current design allows setting of a [transfer stop as a bus stop property](https://www.figma.com/file/dsNMixsO1558hCX0XzRDrc/Bus-stops-%7C-JORE-4.0-UX?type=design&node-id=1118%3A60691&t=YpTaINsx6NubuLns-1). The property is also displayed in [the header of a stop](https://www.figma.com/file/dsNMixsO1558hCX0XzRDrc/Bus-stops-%7C-JORE-4.0-UX?type=design&node-id=1040%3A56391&t=YpTaINsx6NubuLns-1).
