### ISSUE TITLE
As a information planner I want a reasonable solution of making maps to static information installers

### ISSUE THREAD

**Issue by ossiberg** [HSLdevcom/jore4#257]
Is Jore the right software solution?

**Comment by juhakolari** [comment]
Design considerations:
- The user should be able to display search results on the map.
- The map view should have a filter feature, which would display/hide a bus stop label (Proposed in [Figma](https://www.figma.com/file/dsNMixsO1558hCX0XzRDrc/Bus-stops?node-id=733%3A37674&t=fGoa3UESCckkRdQQ-1))  
- It should be tested, how the browser's print feature works with the current map implementation to produce a PDF or a print of the map.
