### ISSUE TITLE
As a public transport planner I want that Jore4 supports also arrival time for stop, not only departure time.

### ISSUE THREAD

**Issue by ossiberg** [HSLdevcom/jore4#259]
This is required for digitransit so that for routes on which passenger leaves the vehicle at a timing point that has some loading time, the time of leaving could be shown based on the arrival, not the departure time.

--

Design proposal: [Arrival times can be selected to display on top of departure times](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=3238%3A256518) (Figma)

**Comment by juhakolari** [comment]
[Arrival times can be selected to display on top of departure times](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=3238%3A256518) (Figma)
