### ISSUE TITLE
As a public transport planner I want to create an empty timetable for a route for a time period

### ISSUE THREAD

**Issue by ossiberg** [HSLdevcom/jore4#260]
For example, if route is not driven on certain day. Nowadays in Jore3 this is needlessly complex.

In other words, I want to override a time period of timetables with emptiness.

--

[Proposal for route-specific day settings](url) (Figma)

**Comment by juhakolari** [comment]
The solution to this gravitates towards [the settings we use](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=2956%3A207208) (Figma) to specify special days, including holidays and school days. The selection for a selected period includes "No scheduled departures" (Ei liikennöintiä). 

Open questions: The current settings page does not require the user to set priority to the settings. Does this result in issues? Also: The special day settings should somehow be indicated also on the version timeline and table.
