### ISSUE TITLE
Create a method to combine infrastructure networks

### ISSUE THREAD

**Issue by haphut** [HSLdevcom/jore4#268]
#218 

As a developer
I wish to build upon existing work for combining infrastructure networks
so that we can save loads of development effort.

This ticket is done when
- Fixup layer process is tested and digiroad + fixup layer is working together

**Comment by haphut** [comment]
Status update: Trying [hootenanny](https://github.com/ngageoint/hootenanny). Hootenanny requires data in OSM format.

I'm using [ogr2osm](https://github.com/roelderickx/ogr2osm) to transform Digiroad into OSM. Packaging with Docker was not effortless. The code required small changes also. Still working on this so I haven't uploaded anything yet.

While waiting for data from the city of Helsinki, I'm trying to get the tram network from OSM. Using Osmosis to cut it out.

Hootenanny takes hours to run on a beefy laptop with default settings and a bit too large of a network. Single-threaded.

**Comment by haphut** [comment]
![image](https://user-images.githubusercontent.com/4615413/114663810-8bbfd600-9d03-11eb-8ac3-d79943c39b10.png)
The blue lines are roads from Digiroad. The green dashed lines are tram tracks from OSM. The background map is from Digitransit (OSM).

Digiroad models both Helsinginkatu and Kaarlenkatu as single links. On Kaarlenkatu the trams move among the cars. On the other hand, on Helsinginkatu the trams have their own section in the middle of two separate car lanes.

Action alternatives:
- Find space for trams between the car lanes in Helsinginkatu. Try to use the property data (lanes, width) of Digiroad imaginatively.
- Use another street data source than Digiroad for Helsinki where the current tram tracks are. Espoo will need handling soon.
- Keep tram tracks as a separate network and abandon the idea of conflation.

**Comment by haphut** [comment]
Digiroad documentation says:
```
4.4.6 Width
Definition
Road width is the width of the part of the carriageway meant for vehicle traffic. On paved roads the carriageway is often separated from the shoulders with a white border line. If a border line doesn’t exist, the width equals the width of the paving. On gravel roads the width equals the width of the whole road, since gravel roads don’t have shoulders.

Values
Arvo (value) field indicates the value of the width (cm).

Coverage
Information is available for all road links except driving path, walking and cyckling paths and ferrys.
```

Yet this property information was not released in [the extract `2021_01`](https://aineistot.vayla.fi/digiroad/2021_01/):
```
$ for shpfile in *shp; do ogrinfo -so -al "${shpfile}"; done | grep -i leveys
INFO: Open of `DR_SUURIN_SALLITTU_LEVEYS_K.shp'
Layer name: DR_SUURIN_SALLITTU_LEVEYS_K
```

The right layer is available in extract `2021_02`, though.

**Comment by haphut** [comment]
In extract `2021_02`, the width value is 400 cm for Kaarlenkatu and 500 cm for Helsinginkatu in the links depicted in the image. So it seems that the values do not take into account whether the street is split in two by the tram tracks.

**Comment by haphut** [comment]
![image](https://user-images.githubusercontent.com/4615413/115231377-28c4a980-a11e-11eb-8816-e79ba1fe1fb8.png)
Also the amount of lanes is missing from many links.

**Comment by haphut** [comment]
Conflating tram tracks into Digiroad links so that separate tram tracks stay separate seems very hard to do automatically.

Instead, it might be possible to conflate all tram tracks with Digiroad so that all tram tracks and roads follow the same geometry regardless of whether the tram tracks are separate from the road in the physical world.

Though that is not trivial either, as in the northern Mäkelänkatu there are two Digiroad links with two tram tracks in between and in Helsinginkatu there is just one Digiroad link with two tram tracks in between.

**Comment by haphut** [comment]
From a discussion regarding mapping tram tracks in OSM ( https://help.openstreetmap.org/answer_link/2308/ ):
> Q: So one page proposes using one way, and tagging it both as a street and as a tram track, the other proposes creating a new way, reusing the nodes of the existing way for the street. This seems in contradiction. What is the best approach?
> A: The first method is recommended (having an extra way for the tram track). There are several reasons for this:
>   - there are tags that can be meaningful for tram tracks and highways (e.g. oneway), so conflicts are possible;

If there are one-way tram tracks on a two-way road or vice versa, we should consider it in the data model.

One way is to copy each two-way road as two one-way roads with possible tram tracks included.

Another way is to keep the tram track and the road networks separate except for retaining a connection between the corresponding infrastructure link IDs.

**Comment by haphut** [comment]
![image](https://user-images.githubusercontent.com/4615413/116185040-82823080-a729-11eb-8f63-c798447ecc38.png)
An image visualizing Mäkelänkatu for comparing to the situation in Helsinginkatu. Blue lines for Digiroad, brown lines for OpenStreetMap tram tracks.

**Comment by haphut** [comment]
The Hootenanny experiment has a repository now: https://github.com/HSLdevcom/jore4-hootenanny-experiment

**Comment by haphut** [comment]
`hootenanny convert` transforms Digiroad coordinates into WGS-84 automatically when transforming to OSM format.

**Comment by jschummer** [comment]
As a side note, it was noticed that some part of the tram network is needed for the bus routes to be modeled too. This is because some bus lines use the road "on top of" the tram tracks, especially at and around stops.

These road segments are not open for private cars and some / most of them have been found not to be included in the Digiroad data.

Possible the relevant road segments can be modeled manually first, until the actual tram network is imported.
