### ISSUE TITLE
Clarify which spatial data should be managed in Jore4

### ISSUE THREAD

**Issue by eetuseta** [HSLdevcom/jore4#27]
As a team we need to know what the vision & strategy behind location details is so that we can develop the product in the right direction

To achieve this we need a meeting with stakeholders on this issue where it is discussed

**Comment by haphut** [comment]
1. What spatial data should Jore4 be the master system for?
1. What should be handled by e.g. the map team separately?
1. What should be the update process for street data, for example?
1. Which data sources to use for what? OpenStreetMap, Digiroad, municipal sources, something else?
