### ISSUE TITLE
As a developer, I'd like the cloud infra to be documented visually

### ISSUE THREAD

**Issue by jschummer** [HSLdevcom/jore4#275]
The documentation should also include IP-addresses and/or DNS-names where applicable.

The purpose of the doc is to document the infra and to ease the developers' lives when they need to check e.g. host names.

**Comment by haphut** [comment]
Related resources:
- Network Watcher in Azure: <https://docs.microsoft.com/en-us/azure/network-watcher/view-network-topology>
- Some PowerShell script using Network Watcher: <https://github.com/PrateekKumarSingh/azviz>

**Comment by haphut** [comment]
Maybe the image could be updated on every push to `main` of https://github.com/HSLdevcom/jore4-deploy . One can run PowerShell in GitHub Actions by changing `shell`: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell .

Although I'm not sure what kind of Azure access we would need to give to GitHub Actions to make that happen.
