### ISSUE TITLE
As a Developer I want to experiment with map matching Jore 3 link shapes onto Digiroad road network with QGIS

### ISSUE THREAD

**Issue by lassemaatta** [HSLdevcom/jore4#306]
Source geometry: Jore 3 link shape (`jr_point`) for a road link (or links)
Target geometry: Digiroad road network
Tool: [Hootenanny](https://github.com/ngageoint/hootenanny) or similar map-matching tool

**Comment by haphut** [comment]
I did not check during the backlog refinement but I think that OSRM and Graphhopper have map matching capabilities.

HSL custom tools: https://github.com/HSLdevcom/jore-geometry-matcher and https://github.com/HSLdevcom/jore-geometry-matcher

**Comment by haphut** [comment]
Other tools from https://github.com/topics/map-matching :

https://github.com/bmwcarit/barefoot Looks popular yet unmaintained. From BMW.

https://github.com/cyang-kth/fmm "Fast map matching". By a KTH student. Reads both shapefiles and OSM format. Has a UI.

https://github.com/jagodki/Offline-MapMatching QGIS plugin for map matching.

https://github.com/arthurdjn/noiseplanet For OSM.

**Comment by haphut** [comment]
The QGIS plugin approach seems like a dead end. I'll write about it in detail later.

**Comment by haphut** [comment]
The QGIS plugin ( https://github.com/jagodki/Offline-MapMatching ) is too slow to handle even a small area of Digiroad and one shortish route within two hours on a fast laptop. No go.

I'm currently building the Docker image for https://github.com/cyang-kth/fmm . It seems promising from a short glance at Google Scholar and the paper abstract.

**Comment by haphut** [comment]
There is now a verbosely named repository in https://github.com/HSLdevcom/jore4-digiroad-gtfs-map-matching-experiment

**Comment by haphut** [comment]
Closing as QGIS was already tried. There are other tools being tried at the moment.
