### ISSUE TITLE
Create a new entrypoint for jore4-hasura image that can read secrets as files

### ISSUE THREAD

**Issue by pallost** [HSLdevcom/jore4#323]
The current jore4-hasura image only runs migrations if the HASURA_GRAPHQL_DATABASE_URL environment variable is defined.. which we cannot (nicely) build from secret files

**Comment by haphut** [comment]
The official `ENTRYPOINT` at `/bin/docker-entrypoint.sh` cannot read CLI arguments while `CMD` can. The official entrypoint is responsible for SQL schema migrations. That is why we need to feed the official entrypoint the environment variables.

@pallost explained this idea in a video chat. We create our own shell script as entrypoint and add it into our Hasura image. Our entrypoint script could look something like:
```sh
#!/bin/sh
FOO="$(cat /bar)" \
  BAZ=... \
  exec /bin/docker-entrypoint.sh
```

Especially `HASURA_GRAPHQL_DATABASE_URL` is needed.
