### ISSUE TITLE
Specify Kubernetes probes for Hasura

### ISSUE THREAD

**Issue by haphut** [HSLdevcom/jore4#324]
As a developer I wish to specify appropriate Kubernetes probes for Hasura so that other services know when Hasura is healthy and ready to serve and so that Hasura gets to finish SQL migrations.

**Comment by pallost** [comment]
https://github.com/HSLdevcom/jore4-flux/pull/17 intruduced readiness and liveliness probes, but it does not make a difference between the /healthz endpoint's 200 OK and 200 WARN responses

**Comment by haphut** [comment]
It seems to my untrained eye that currently `httpGet` cannot differentiate between `200 OK` and `200 WARN` and we would need `exec` instead: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#probe-v1-core .
