### ISSUE TITLE
As a developer I would like to evaluate Leaflet as a map library

### ISSUE THREAD

**Issue by pallost** [HSLdevcom/jore4#328]
Requirements can be found from this ticket: https://github.com/HSLdevcom/jore4/issues/26

**Comment by tk-vincit** [comment]
Leaflet was somehow tested in [jore4-graphql-playground](https://github.com/HSLdevcom/jore4-graphql-playground) repository.
As commented in https://github.com/HSLdevcom/jore4/issues/26#issuecomment-857561587 the team made common decision to use Leaflet as map library. Thus this issue can be closed for now.
