### ISSUE TITLE
Improve naming conventions of Azure's secrets

### ISSUE THREAD

**Issue by tk-vincit** [HSLdevcom/jore4#330]
Naming conventions of secrets in Azure should be checked + improved.

We have secrets like `hsl-jore4-hasura-password ` `hsl-jore4-hasura-username`, and it's a bit unclear if they refer to Hasura's admin username and password or db's username and password or perhaps even something else..?

Also do we need e.g. both `hsl-jore4-dev-db-database` and `hsl-jore4-public-db-database`? Each environment should have their own vault so we shouldn't need environment specific secrets.

**Comment by pallost** [comment]
the hsl-jore4-dev-db-database is actually just forgotten there after the policy changed to use "public" instead

**Comment by pallost** [comment]
the "db-" prefix is implemented in this pull request: https://github.com/HSLdevcom/jore4-deploy/pull/40
