### ISSUE TITLE
Add robots to jore4 github repositories to standardize all operations (e.g. repo settings, reviews, etc)

### ISSUE THREAD

**Issue by pallost** [HSLdevcom/jore4#359]
Standardizing repository settings: https://github.com/probot/settings

**Comment by tk-vincit** [comment]
Please also pay attention to "Security Implications" mentioned [here](https://github.com/apps/settings):
>WARNING: Note that this app inherently escalates anyone with push permissions to the admin role, since they can push config settings to the master branch, which will be synced. In a future, we may add restrictions to allow changes to the config file to be merged only by specific people/teams, or those with admin access (via a combination of protected branches, required statuses, and branch restrictions). Until then, use caution when merging PRs and adding collaborators.
