### ISSUE TITLE
Separate SQL schema migrations from Hasura

### ISSUE THREAD

**Issue by haphut** [HSLdevcom/jore4#365]
As a developer, I want to use a separate tool for SQL schema migrations so that I can use all PostgreSQL capabilities for SQL schema migrations and so that the responsibilities of components are clear.

Some requirements:
- can run non-transactional migrations to avoid availability issues (e.g. can run `CREATE INDEX CONCURRENTLY`)
- supports up-down linear migrations
- migrations are written as SQL files
  - so that we can use advanced PostgreSQL features and optimizations, e.g. exclusion constraints, extended statistics, partial indexes, expression indexes, index operator classes etc. that no DSL supports
  - so that the SQL files can be separately put through formatting, linting and other static analyses
- we can run string interpolation to replace SQL usernames at runtime when authorizing access to schemas

Nice-to-haves:
- psql support is nice. `\copy` might become useful with test data sets and test runs.

**Comment by pallost** [comment]
I've been using `knex` in many projects. It's not SQL syntax, but pretty straightforward to use however. The nodejs syntax allows us to use parameters and even calculations within the migration scripts. http://knexjs.org/#Migrations-API

**Comment by haphut** [comment]
I updated the list of requirements after @pallost commented on it.

I would hold on very tightly to the ability to use any PostgreSQL features: multiranges in PG14 for valid times of a route, ensuring no overlap between valid times of a route with exclusion constraints, creating localized indexes for languages and timezones using partial and expression indexes, speeding up queries with extended statistics...

Having a uniform syntax for PostgreSQL features practically requires using the PostgreSQL flavour of SQL and PL/pgSQL.

**Comment by haphut** [comment]
Flyway pros:

- supports migrations in plain SQL
- supports up-down linear migrations
- supports non-transactional migrations, at least to some degree
- lists some of its [limitations](https://flywaydb.org/documentation/database/postgresql#limitations)
- the team has previous experience in it

Cons:
- migrations are based on parsing the SQL which means that Flyway will lag behind PostgreSQL syntax
- has [no support for psql](https://flywaydb.org/documentation/database/postgresql#limitations) due to JDBC
- the schema where an extension is installed [cannot be changed](https://flywaydb.org/documentation/database/postgresql#limitations) with Flyway once set the first time

I dislike that Flyway tries to parse the SQL code. From their [documentation](https://flywaydb.org/documentation/knownparserlimitations):

> We frequently get bugs about the Flyway parser being unable to handle certain sql scripts.

If the parser chokes on some SQL construct or the [non-transactional migration regex matcher](https://github.com/flyway/flyway/blob/80e2006a44bd6c8c3fd2655a06405b03a3bb61bc/flyway-core/src/main/java/org/flywaydb/core/internal/database/postgresql/PostgreSQLParser.java#L31) is lacking, you cannot run that migration. Better file an issue and wait for the next Flyway release, eh? :stuck_out_tongue: 

Also, using Flyway placeholders, e.g. `${foo}`, would prevent any static analysis tools from analyzing the SQL migration files as they would no longer be valid SQL. I suggest to keep using the homemade string interpolations from `jore4-hasura` for username replacement. The "porting" between repositories should consist of copying the script and its tests and running the script somewhere in `ENTRYPOINT`.

**Comment by haphut** [comment]
Some alternatives with explicit non-transactional migration support:

- https://github.com/thomwright/postgres-migrations
  - design principle: no down migrations, "roll forward" instead of "roll back"
- https://github.com/yandex/pgmigrate/blob/master/doc/tutorial.md
