### ISSUE TITLE
As a business owner I want to find out if hand drawn network could be licensed according to our wishes

### ISSUE THREAD

**Issue by ossiberg** [HSLdevcom/jore4#400]
Case when we make a fix layer for digiroad, can we draw the fix layer on top of some other map? Which map?

Needs legal advice

**Comment by haphut** [comment]
If you get legal advice regarding OSM usage in Finland, it's valuable to write them down somewhere public as there are other organizations who would benefit from that legal advice.

**Comment by ossiberg** [comment]
Hei,

 

Äskeisessä palaverissa selvisi, että OpenStreetMap-aineistoa käytetään Jore4-projektissa ainoastaan HSL:n sisäisenä työnaikaisena ”apuväline-taustakarttana” reittiviivojen muodostamista varten. Kolmansille osapuolille/yleisölle luovutetaan ainoastaan reittiviivat/-pisteet ilman taustakarttaa.

 

Koska HSL ei JOREn yhteydessä saata OpenStreetMap -aineistoa tai sen osia yleisön saataviin sellaisenaan tai muutettuna, vaan ainoastaan käyttää aineistoa apuvälineenä, en näe tekijänoikeudellista ongelmaa kuvatussa tilanteessa.

 

Tässä vielä relevantti pykälä kokonaisuudessaan eli tekijänoikeuslain 2 §:

 

Tekijänoikeus tuottaa, jäljempänä säädetyin rajoituksin, yksinomaisen oikeuden määrätä teoksesta valmistamalla siitä kappaleita ja saattamalla se yleisön saataviin, muuttamattomana tai muutettuna, käännöksenä tai muunnelmana, toisessa kirjallisuus- tai taidelajissa taikka toista tekotapaa käyttäen.

 

Kappaleen valmistamisena pidetään sen valmistamista kokonaan tai osittain, suoraan tai välillisesti, tilapäisesti tai pysyvästi sekä millä keinolla ja missä muodossa tahansa. Kappaleen valmistamisena pidetään myös teoksen siirtämistä laitteeseen, jolla se voidaan toisintaa.

 

Teos saatetaan yleisön saataviin, kun:

 

1) se välitetään yleisölle johtimitse tai johtimitta, mihin sisältyy myös teoksen välittäminen siten, että yleisöön kuuluvilla henkilöillä on mahdollisuus saada teos saataviinsa itse valitsemastaan paikasta ja itse valitsemanaan aikana;

 

2) se esitetään julkisesti esitystapahtumassa läsnä olevalle yleisölle;

 

3) sen kappale tarjotaan myytäväksi, vuokrattavaksi tai lainattavaksi taikka sitä muutoin levitetään yleisön keskuuteen; taikka

 

4) sitä näytetään julkisesti teknistä apuvälinettä käyttämättä.

 

Julkisena esittämisenä ja yleisölle välittämisenä pidetään myös esittämistä ja välittämistä ansiotoiminnassa suurehkolle suljetulle piirille.
