### ISSUE TITLE
As a developer, I'd like to access Azure environments via bastion host permanently

### ISSUE THREAD

**Issue by jschummer** [HSLdevcom/jore4#417]
Bastion hosts experience this error after some time of being up and running: https://github.com/MicrosoftDocs/azure-docs/issues/47302

I.e. developers trying to ssh into the bastion host get the error `Your account has expired; please contact your system administrator`.

This should not happen. Instead, bastion hosts should be accessible to developers for the time of their existance.

One possible solution could be to adjust the settings of the bastion host at the time of its creation, to prevent the credential in question from expiring.

**Comment by pallost** [comment]
Could disable account expiration with `sudo chage -E -1 -M -1 hsladmin`. We anyway only use SSH keys for logging in.
