### ISSUE TITLE
As a public transport planner I want that Jore is able to handle additional trip(s) ordered for a school group or similar

### ISSUE THREAD

**Issue by ossiberg** [HSLdevcom/jore4#427]
A variant of user story #426. Sometimes includes a trip that is doubled for capacity reasons (two buses run the same trip: same route and same timetable)

--
In Hastus import, adding a trip instead of replacing it is in the design. Doubling a trip _within_ JORE4 is not (and might present sync problems?)

Design proposal for displaying doubled trips: 
A) Doubled/tripled e.g. trips could be indicated as superscript next to the departure time -> **10** 11<sup>x3</sup>. 
**Option B) selected** A simple option for doubled trips would be to just double the departure times -> **10** 11  11

**Comment by juhakolari** [comment]
Design proposal: 
A) Doubled/tripled e.g. trips could be indicated as superscript next to the departure time -> **10** 11<sup>x2</sup>. 
B) A simple option would be to just double the departure times -> **10** 11  11
