### ISSUE TITLE
As a product owner I want to document the options the user has for the line type and how it affects the coloring

### ISSUE THREAD

**Issue by ellinooraikaheimo** [HSLdevcom/jore4#431]
Relates to defining the compulsory information for the line. 

Line type (linjan tyyppi) options vary depending on the selection made to the part "joukkoliikennekohde”. (Esim. Kun valinta joukkoliikennekohteeksi on bussi tuo se linjan tyyppi -kohtaan mm vaihtoehdon runkolinja. Tämä valinta vaikuttaa linjan värin visualisointiin)

**Comment by ossiberg** [comment]
https://github.com/HSLdevcom/jore4/blob/main/wiki/linetype.md This possibly answers the question
