### ISSUE TITLE
As a product owner & designer I want to specify the MVP level search filters that are needed to the Routes and lines main page

### ISSUE THREAD

**Issue by ellinooraikaheimo** [HSLdevcom/jore4#437]
Define the filters (MVP + nice to have) that the user will have available in the Routes and Lines main view, within the search functionality.

[Preliminary UX on search (Figma)](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=2192%3A79880)

(PO can comment ideas/thoughts in Figma: https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=1503%3A45119)

Issue can be further discussed in a design meet.

**Comment by ossiberg** [comment]
Added a comment to figma. MVP includes ability to:
- search (or filter) by route number or part of it (read: 14 includes routes 14, 146, 147, 147A, 614 etc)
- search (or filter) by mode (such as all trains)
