### ISSUE TITLE
As a product owner and designer I want to specify the MVP level network viewing settings for showing bus stops in the map-based workspace

### ISSUE THREAD

**Issue by ellinooraikaheimo** [HSLdevcom/jore4#438]
E.g. Merkityt (mastossa), merkitsemättömät, (ei maastossa), tulevat, nykyiset, poistetut

PO can comment ideas/thoughts in Figma: https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=1128%3A184

Can be discussed further on a design meet

**Comment by ellinooraikaheimo** [comment]
In case @ossiberg already has a vision about the mvp filters for showing bus stops you could type them here or we can discuss this in the upcoming design meet. This came accross while roughly estimating the completion of the routes and lines mvp. Assumably at least public transport species (joukkoliikennelaji) but also others?

**Comment by ossiberg** [comment]
@ellinooraikaheimo 

For MVP, I think filtering by validity is enough (Tulevat/Nykyiset/Poistetut). 

When we add other modes of transport (metro, train etc.), I prefer this word over Jore3 "joukkoliikennelaji" then that is useful, but I would not include this in MVP
