### ISSUE TITLE
User can edit the line information

### ISSUE THREAD

**Issue by ellinooraikaheimo** [HSLdevcom/jore4#468]
In the main page of the line, the user can select Edit in order to change the information. 

A separate view to edit the information opens up. After editing, the user has options to save or cancel.

[Bus line information edit view (Figma)](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=2041%3A76777)

[Bus line main view (Figma)](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=2039%3A74233)

**Comment by jpeuralinna** [comment]
Editointi toimii, mutta formista puuttuu figmassa olevat nimiversiot, joukkoliikennekohde, linjan tyyppi sekä linjan vastuuhenkilöt. Onko näille olemassa oma korttinsa?
