### ISSUE TITLE
User can see the main page of the line with routes

### ISSUE THREAD

**Issue by ellinooraikaheimo** [HSLdevcom/jore4#469]
User sees the routes listed under in the main page of the line.

Route main information is presented in a main row as follows:

- Route direction
- Route number
- Route name
- Validity period
- Last edited
- Map icon button to open the route in a viewing mode in a map (separate modal)
- Collapse icon button (by default the bus stops are not shown)

List of bus stops included to the route, are presented under the route with collapse icon button with the following information:

- Short code
- Bus stop name
- Validity period
- Last edited
- Hastus code (e.g. 1RT)
- Whether bus stop is used as "ajantasauspysäkki". ( marked as (A) after the hastus code)
- Menu icon button with the options

MVP approach to show routes and route directions as a list. (Later filters will be added)

[Line view (Figma)](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=2039%3A74233)

Depends on: #508

**Comment by pallost** [comment]
Partially implemented in: https://github.com/HSLdevcom/jore4-ui/pull/73
Missing parts are: route direction, last edited, hastus code as these are missing from the current version of the datamodel
