### ISSUE TITLE
User can edit the route information

### ISSUE THREAD

**Issue by ellinooraikaheimo** [HSLdevcom/jore4#471]
In the line main page, the user can edit the route information, by clicking the pen icon button next to the route name. A separate dialog for route information opens up.

User can see and edit the following information:

- Route name
- Route length
- Route name
- Name variants
- Routes connection to a line (within which line the route is created)

User has options to save, cancel and delete the route.

[Dialog for editing route information in list view (Figma)](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=2039%3A76080)

**Comment by jpeuralinna** [comment]
Editing the information works fine, but some of the information listed in the description is missing ("Route length" and "Name variants"). Is there an additional ticket for those?

**Comment by jpeuralinna** [comment]
Ticket for remaining fields: https://github.com/HSLdevcom/jore4/issues/676
