### ISSUE TITLE
As a public transport planner, I want to see intuitively what a timetable of a route on a selected day would look like after uploading schedules

### ISSUE THREAD

**Issue by ossiberg** [HSLdevcom/jore4#487]
Needs design

Arttu's ideas:
… so that I can verify whether uploading vehicle schedules, or especially appending to existing schedules, really had the desired effect or whether it resulted in deleted or duplicated trips. 

For instance, let’s say that the Independence Day eve, 5.12. has Sunday schedules by default, but additional trips (-> exceptional vehicle schedules) on some but not all routes. Or I might need to amend schedules of an individual, ordinary weekday, involving additional trips on some routes due to a large event in the city. In these cases I’m not uploading the schedules of a season and my routes “from scratch” but updating the schedules of just some routes/trips while letting others as they were. 

In addition to Jore4 enforcing some basic constraints, validity periods, eliminating completely duplicated trips and so on, I would like to have a visual proof that the operations will look just like I planned on a specific calendar date (not day type!) that I know to contain exceptions (or alternatively, a date that should be completely normal). 

E.g. select the desired route patterns (and a checkbox whether to include draft schedules or production ones only) -> see a calendar grid that visualizes the total number of trips on each operating day with fill color (here I would quickly see if a whole lot of trips are duplicated) -> on mouseover, show the exact total nr of trips on that day -> on mouse click, open a list to the side that shows the individual trips ordered by departure time and route pattern (-> optionally, click an individual trip to see its stop times). 

-- 

[Current design highlights changes in the amount of trip in the Hastus import summary](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=2866%3A209421) (Figma)

**Comment by juhakolari** [comment]
@ossiberg There seem to be some conflicting (or perhaps add-on) requirements that require iteration.

**Placement**. The preferred placement for the feature would appear to be the search and the way the search results are displayed, although immediate feedback after Hastus import could be considered as well.

**Comparison**. Is a comparison to the number of trips in previous version a requirement, or only the number of current trips? A previous benchmark seemed to indicate displaying previous version as well:

![image 45](https://user-images.githubusercontent.com/77674841/146196496-a9a9771c-97be-4daf-ab18-d7fbda785751.png)

**Date range**. The situation on a given date, as mentioned in the description, is a current feature of the design, at least on line/route level.  In addition, the description includes "a calendar grid that visualizes the total number of trips on each operating day with fill color”. This indicates a different approach; the search should include a date range as well as a specific date.

**Layout**. From the description: "on mouseover, show the exact total nr of trips on that day -> on mouse click, open a list to the side that shows the individual trips ordered by departure time and route pattern (-> optionally, click an individual trip to see its stop times).” -> Clicking on a trip would be preferable to a new view that places the calendar grid
