### ISSUE TITLE
As a public transport planner I need to see stops of a route on a map

### ISSUE THREAD

**Issue by ossiberg** [HSLdevcom/jore4#503]
- [x] Import Jore3 stops with Jore3 importer to jore3 schema
- [x] #492  
- [x] Configure Hasura to access stops from Jore4 database
- [x] In frontend, fetch stops from Hasura and show them on top of the map when needed (supports for example #501)

**Comment by jpeuralinna** [comment]
Moved this from "To be deployed" to project backlog, since 2 of the tasks are not marked as done.

**Comment by eleksi** [comment]
I don't think those tasks are relevant to this card. They are some ancient tasks that I didn't bother checking as I didn't complete them. I will remove them from this card if it is better.
