### ISSUE TITLE
Specify overall search logic

### ISSUE THREAD

**Issue by ellinooraikaheimo** [HSLdevcom/jore4#506]
Keep design specification workshop with Lari and Joona, to create overall vision about the search logic.

[Preliminary specification](https://docs.google.com/drawings/d/1N_hkowDrtRM4T6K7JxyUO0WxG9vw0hUSU1gGCdNzL9M/edit) (Google Drawings)

[Search in Routes and lines UI](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=3427%3A301089) (Figma)

[Search in Timetables UI](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=3238%3A255268) (Figma)

[Search in Map mode](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=3826%3A298731) (Figma draft)

- [x] UI/UX design
- [x] Iteration with selected users (at least m-info)

**Comment by juhakolari** [comment]
MVP specification done.
