### ISSUE TITLE
As a product owner I want to make a final  check if design for route and data model of it supports all usually used exceptions

### ISSUE THREAD

**Issue by ossiberg** [HSLdevcom/jore4#528]
Check https://github.com/HSLdevcom/jore4/blob/main/wiki/routes.md and make sure that everything is has a ticket.

**Comment by ellinooraikaheimo** [comment]
Note: Additions to the data model will be added once the implementation reaches the timetables module. The listed cases & suggested workflows can be checked in a design meet

**Comment by ellinooraikaheimo** [comment]
Discussed approaches to cover the listed cases are added at the end of the linked wiki document.
