### ISSUE TITLE
Add map matching and map matching db to e2e setup

### ISSUE THREAD

**Issue by jpeuralinna** [HSLdevcom/jore4#544]
We should include map matching to our e2e test setups.

- [x] add map matching to e2e setup action
- [x] add map matching db to e2e setup action
- [x] add e2e tests to map matching cd.yml
- [x] add e2e tests for map maching db

**Comment by pallost** [comment]
e2e setup action changes are in this PR: https://github.com/HSLdevcom/jore4-flux/pull/58

**Comment by pallost** [comment]
e2e tests added to map-matching: https://github.com/HSLdevcom/jore4-map-matching/pull/13 (depends on HSLdevcom/jore4-flux#58)

**Comment by pallost** [comment]
e2e tests for map-matching database seems to have already been added previously: https://github.com/HSLdevcom/jore4-postgres/blob/main/.github/workflows/cd.yml#L160
