### ISSUE TITLE
As user I want to stay logged in for the whole day

### ISSUE THREAD

**Issue by tk-vincit** [HSLdevcom/jore4#560]
... or as long as PO deems reasonable.

Currently user session experies in an hour (or something like that) and after that api calls start to fail, which is really bad for UX.

Probably we want to refresh session periodically or so, and in case api starts to return "unauthorized" responses and we can't refresh session anymore for some reason then user should be redirected to login page.

**Comment by jschummer** [comment]
The session timeout was accidentally set to 30 min (spring boot update changed the property name which set the timeout).

This was fixed and the timeout is not 6 hours.

The remainder of the ticket content might still be valid in spite of the fix.
