### ISSUE TITLE
As a frontend developer, I'd like to know what kind of logging solution we'll use in production code

### ISSUE THREAD

**Issue by jschummer** [HSLdevcom/jore4#565]
Existing direct `console.log` statements in frontend code should probably be changed to use a better solution.

**Comment by jschummer** [comment]
Possible solutions might be sentry or Azure monitor (https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript#sending-telemetry-to-the-azure-portal)

**Comment by pallost** [comment]
Azure Application Insight is already collecting data from VMs, Kubernetes, docker containers, databases, etc to a single Log Analytics Workspace. It would be pretty easy to integrate also Frontend data collection to AppInsights

**Comment by pallost** [comment]
Sentry seems to be able to do all these features as well.

**Comment by pallost** [comment]
The subject was discussed in the architecture meeting: https://github.com/HSLdevcom/jore4/blob/main/wiki/architecture-meetings.md#2022-02-09-architecture-meeting slight preference was towards azure app insights which was confirmed by the customer as well. 
Created follow-up implementation ticket: https://github.com/HSLdevcom/jore4/issues/610
