### ISSUE TITLE
As user I want stop creation flow to be intuitive

### ISSUE THREAD

**Issue by tk-vincit** [HSLdevcom/jore4#616]
Currently creating stops is clumsy:

- User opens map somehow in edit mode
- User clicks "Create stop"
- User clicks somewhere in map to add stop. Stop is now visible in map, but not yet saved anywhere (!)
- User clicks "edit" button on the popover which opened next to the stop
- User enters stop details
- User clicks "save" button

After all these steps stop is finally saved to db.

Plan/design the ideal case how this should happen.

As discussed on [Slack](https://vincit.slack.com/archives/CNG9QULAH/p1645080238607429?thread_ts=1645009423.240579&cid=CNG9QULAH):
- let's open the Stop editing modal immediately after the stop has been created

- if the user clicks Cancel, the draft bus stop should be deleted

**Comment by eleksi** [comment]
We probably want to use camera setting "padding" when panning the map with modal open. Padding is available in react-map-gl v7, we have v6. v7 also has performance enhancements etc. so we probably want to upgrade the library. The upgrade can't be done yet, since react-map-gl-draw [does not yet support react-map-gl v7](https://github.com/uber/nebula.gl/issues/725).

**Comment by jpeuralinna** [comment]
Created couple tickets regarding stops:
[After a stop is moved, the information box stays at the old location #697](https://github.com/HSLdevcom/jore4/issues/697)
[Improve visualisation of connection between stops and infrastructure links. #698](https://github.com/HSLdevcom/jore4/issues/698)
[When user clicks map while a stop is selected, a new stop is created at the point clicked. #696](https://github.com/HSLdevcom/jore4/issues/696)
[When creating a new stop or moving existing stop on "left" side of one-way street causes "postgres tx error" #695](https://github.com/HSLdevcom/jore4/issues/695)

**Comment by eleksi** [comment]
Blocked by #657
