### ISSUE TITLE
Check for validity and priority conflicts on UI before trying to save stops/routes/lines/etc

### ISSUE THREAD

**Issue by pallost** [HSLdevcom/jore4#636]
Remember that there are cases 

- where we want to edit existing stops/routes/lines (so have to exclude them from the filter)
- where we want to create a new instance of an entity (so should find them all)

[Design proposal for overlaps](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=4122%3A319880) (Figma)
[Selecting between substitution and a new version when saving ](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=4122%3A319878)(Toggle in Figma)

**Comment by jschummer** [comment]
NB that this
- should take into account that there can be more than one draft-level version (valid at a given time)
- that the DB has not been adjusted yet to take this multiple-draft-version-functionality into account (pending ticket #634 )
