### ISSUE TITLE
Visualize the cases "Pisto" and "Silmukka" when drawing a route

### ISSUE THREAD

**Issue by ossiberg** [HSLdevcom/jore4#647]
Iterate with design how to show the rare cases "Pisto" and "Silmukka" for the user.

Arrows or something else? Mvp approach - no over engineering preferred.

Discuss implementation with team, benchmark JoremapUI. 

It was decided that arrows should be added.

**Comment by eleksi** [comment]
An offset of few pixels to the right has been added to the route drawn.
