### ISSUE TITLE
Verify that a route's starting/ending bus stop cannot be deleted

### ISSUE THREAD

**Issue by pallost** [HSLdevcom/jore4#650]
Currently the delete cascade removes it from the journey pattern automatically. But it probably also removes the route with it which is not the desired behavior

**Comment by jschummer** [comment]
When checking this, we were not sure if this means a check of the UI carried out at run time or a check to be carried out as a study by a developer.

However, this is our view on the subject as discussed with the PO:
- the db should not delete a route through cascadation when the route's start or end stop point is deleted (this should be verified by a developer as a study)
- the UI should verify at run-time that a stop to be deleted is not the start or end stop point of any route
