### ISSUE TITLE
Show all the stops in the route's list view (also the ones that don't belong to its journey pattern)

### ISSUE THREAD

**Issue by pallost** [HSLdevcom/jore4#654]
User can see the available bus stops with the filter "Näytä kaikki reitin pysäkit". From the menu icon button user can make selection to include the stop to the route.

**Comment by jpeuralinna** [comment]
Seems to work properly, only thing I noticed is that with narrower screens part of the "poista reitin käytöstä" button is left outside of the view.
![image](https://user-images.githubusercontent.com/75245169/160066468-95290456-594b-49f1-8a08-8429c9093f34.png)
I think @ossiberg should decide if it merits a bug/improvement ticket or not.
