### ISSUE TITLE
Research: Upgrade react-map-gl to v7

### ISSUE THREAD

**Issue by eleksi** [HSLdevcom/jore4#657]
Performance updates etc.

Edit: 
We no longer (probably) have to use react-map-gl-draw, switch to using se mapbox-gl-draw directly, as noted in [patch notes](https://visgl.github.io/react-map-gl/docs/whats-new#react-map-gl-v70).

https://github.com/visgl/react-map-gl/tree/7.0-release/examples/draw-polygon

15.6. additions
- https://dev.azure.com/hslfi/JORE%204.0/_wiki/wikis/JORE-4.0.wiki/1990/Map-dependency-rabbit-hole-(UI) 

See also another similar fixed issue: https://github.com/visgl/react-map-gl/issues/1892

- [ ] #1662

Note; This is a research ticket, create implementation ticket within this ticket.

**Comment by tk-vincit** [comment]
This is partially done at https://github.com/HSLdevcom/jore4-ui/tree/wip/upgrade-react-map-gl
Things that are still broken are mentioned in this commit message: https://github.com/HSLdevcom/jore4-ui/commit/2ce7dc971d88c8e2299dea9779ac326a77f87986

**Comment by tk-vincit** [comment]
Seems like `react-mapl-gl-draw` does not (currently?) support `react-map-gl` v7. More details mentioned in commit messages at https://github.com/HSLdevcom/jore4-ui/tree/wip/upgrade-react-map-gl

**Comment by Perholehto** [comment]
Suggesting that we update straightaway to `react-map-gl` version 7.1. There is no problems with backward compatibility in 7.1. It removes need for placeholder dependency and allows us to use `maplibre-gl` types in development. We should also remove dependency `react-map-gl-draw` and directly use `mapbox-gl-draw` instead (https://github.com/visgl/react-map-gl/discussions/2053 , https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-draw/). `react-map-gl-draw` is a wrapper for `mapbox-gl-draw` but in 7.1 we can use it directly so it&rsquo;s not mandatory to use the wrapper. Also `react-map-gl-draw` is not compatible with 7.x versions. We can use <https://github.com/HSLdevcom/jore4-ui/tree/wip/upgrade-react-map-gl> branch for starting point or guidance.
