### ISSUE TITLE
Fetch only visible stops from database

### ISSUE THREAD

**Issue by eleksi** [HSLdevcom/jore4#666]
Split from #629

Currently every stop is fetched regardless of the map viewport. Only fetch stops that are visible.

E.g. do guery with 
https://postgis.net/docs/ST_Within.html

`  service_pattern_scheduled_stop_point(where: {measured_location: {_cast: {geometry: {_st_within: ""}}}})
`

**Comment by jarkkoka** [comment]
Filtering by bounding box could probably be more performant solution with regard to using geometry indices.
