### ISSUE TITLE
Try out Entur Tiamat

### ISSUE THREAD

**Issue by jschummer** [HSLdevcom/jore4#678]
- [x] set up to run locally
- [x] try to run some graphql queries against it
- [x] update findings here https://github.com/HSLdevcom/jore4/blob/main/wiki/Entur_Tiamat_overview.md
- [x] make a proposal if we should go with it

**Comment by culka** [comment]
There are multiple security vulnerabilities with the dependencies used in Entur Tiamat, they should be fixed before we dare to use it.

[dependency-check-report.zip](https://github.com/HSLdevcom/jore4/files/8861698/dependency-check-report.zip)
