### ISSUE TITLE
Research: Study how jore3 stop point CSV-exports can be imported into Entur Tiamat

### ISSUE THREAD

**Issue by jschummer** [HSLdevcom/jore4#680]
Study which way to import stop data to Jore4. Csv or Jore3 importer.

Stop points may be easiest to export from Jore3 via its CSV-export. In case Entur Tiamat is chosen to be the stop module (or the basis for it), it should be checked how this data could be imported into Tiamat on a logical level (which fields required vs which fields provided etc).

Keep in mind that data might need to be versioned (validity time, priority). The versions may need to be linked to Routes and Lines -module's stop points' versions.

Relates to #1074 
Relates to #1649 

Note: Could be implemented in Jore3 importer

Once Tiamat us up, this can be decided.

**Comment by ellinooraikaheimo** [comment]
Note: there is no csv import support in Tiamat. So even if we got the data from Jore3, it is not immediately possible to take into Jore4.

This is another opportunity to import stop information to Jore4, Jore3 importer is another way.

**Comment by culka** [comment]
Possible alternatives explored in the wiki:
https://dev.azure.com/hslfi/JORE%204.0/_wiki/wikis/JORE-4.0.wiki/3445/Jore3-Import#
