### ISSUE TITLE
Hasura won't let save **draft** lines with conflicting validity period

### ISSUE THREAD

**Issue by tk-vincit** [HSLdevcom/jore4#687]
Draft lines/stops/routes should be allowed to be saved even if validity periods are conflicting.

Currenlty we get following error if trying to save draft line with conflicting validity period:
`Exclusion violation. conflicting key value violates exclusion constraint "unique_validity_period"`

**Comment by pallost** [comment]
The issue describing the required implementation detail can be found here: https://github.com/HSLdevcom/jore4/issues/634
