### ISSUE TITLE
When user clicks map while a stop is selected, a new stop is created at the point clicked.

### ISSUE THREAD

**Issue by jpeuralinna** [HSLdevcom/jore4#696]
Steps to reproduce:
1. Go to map view and click "Lisää pysäkki" button
2. Select a existing stop, by clicking it.
3. Click map at some other point.

Expected behaviour:
Stop is unselected, or moved to the point clicked.

Actual behaviour:
A new stop is created at the point clicked.

**Comment by juhakolari** [comment]
To me, the described actual behaviour is the expected behaviour, since the user is expecting to add a new bus stop. 
Also, if selecting an existing bus stop is possible when placing a new one, selection should be prevented. @jpeuralinna
