### ISSUE TITLE
Protect all Azure vnets from accidental deletion

### ISSUE THREAD

**Issue by pallost** [HSLdevcom/jore4#70]
As a Developer, I would like to make sure that all environment's vnet resources are protected from deletion so that peerings and routes to old JORE resources don't get broken.

**Comment by pallost** [comment]
Only Admin users can create vnet peerings between different subscriptions' vnets. So if we accidentally delete a vnet from our environment, the routes get broken to old JORE and we cannot reconnect them without the help of an Admin.

**Comment by pallost** [comment]
Note that locking does not go simply by adding the tag: "critical: yes", but need to lock the resources manually/with an ARM template

**Comment by pallost** [comment]
This is now changed based on this conversation: https://vincit.slack.com/archives/CNG9QULAH/p1614686089055800?thread_ts=1614585227.005700&cid=CNG9QULAH

**Comment by jschummer** [comment]
Sovittiin, että toteutetaan poistonesto kaikille rg:n resourceille, mutta vain prod- ja test-ympäristöissä. Tällä tavalla devops-tyypit voivat jatkossakin vapaasti ja nopeasti tehdä muutoksia dev-ympäristössä.
