### ISSUE TITLE
Show confirmation dialog for moving stops

### ISSUE THREAD

**Issue by pallost** [HSLdevcom/jore4#701]
- [] create a preview map box that shows the change of the location
- [] show the list of routes that are affected by the change

Figma for visualizing the change of the location and confirmation dialog informing the routes that are affected
https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=3073%3A265298

**Comment by jpeuralinna** [comment]
Duplicate ticket.
Implemented in: #699
