### ISSUE TITLE
Merge edit confirmation modals with conflict resolver modal

### ISSUE THREAD

**Issue by pallost** [HSLdevcom/jore4#725]
Currently, the EditStopConfirmationDialog and the ConflictResolverModal are doing somewhat similar things: waiting for user interaction on confirming the edit action and in case of conflicts, resolve them by converting the to draft. It would be a great idea to merge these two and make a generic confirmation & conflict resolver dialog.

- Merged modal in Figma: https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=4931%3A306853

- stop editing in Figma: https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=3073%3A265298
- conflict resolving in Figma: https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=4122%3A319880

**Comment by juhakolari** [comment]
The MVP in this case is only to list conflicts, not resolve in the modal itself. When conflicts are listed, the user can save the update as a draft, correct dates manually elsewhere and return to the draft to save again.
