### ISSUE TITLE
Set video recording for tests so that it creates a separate video for each test.

### ISSUE THREAD

**Issue by jpeuralinna** [HSLdevcom/jore4#744]
Currently video recording for robot tests is done so that it starts recording in the suite setup and then ends when suite is done. So we get one video file for the run.

It would be easier to debug specific tests if the video recording was started in test setup. So we would get separate videos for each test.

Implementation plan:
- figure out the best way to record separate videos for each test. Do we create a new context in each test setup or is there a better way to stop and start recording.
- implement the solution.

**Comment by sr-vala** [comment]
Cypress does not support this. Videos are recorded per spec (test file).
