### ISSUE TITLE
Evaluate cost of choosing Transmodel as a data model

### ISSUE THREAD

**Issue by ossiberg** [HSLdevcom/jore4#752]
HSL wants to know how much time we have lost by choosing Transmodel. Provide also a suggestion of a viable alternative.

Powerpoint slides as outcome

**Comment by jschummer** [comment]
As a general comment, let's try to distinguish between
1. trying to keep the data model somewhat close to TM
2. trying to implement a system that is reusable in other (geographic) contexts
3. using hasura as our main backend for the data model

I'm not trying to say one of them has necessarily caused more work than the others, but it might be useful to try to keep those apart when analysing this issue.
