### ISSUE TITLE
Automatically trigger jore3 importing once a day

### ISSUE THREAD

**Issue by pallost** [HSLdevcom/jore4#755]
Kubernetes allows creating a cronjob resource that can trigger the jore3 import through its HTTP endpoint

See: https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

Depends on the decision regarding the ideal processes (made by HSL) concerning the Jore3 & Jore4 operating simultaneously. Is it necessary to update information to both places and sync to Jore4 or dump data to Jore4 and only update that. Ideally support Jore4 usage.

**Comment by jschummer** [comment]
This may be related to / duplicate of #729 . Not sure why this ticket was closed though.
