### ISSUE TITLE
Switch to using azure-keyvault-secrets-provider addon in Kubernetes

### ISSUE THREAD

**Issue by pallost** [HSLdevcom/jore4#772]
Currently we're manually installing the helm package for the secret provider CSI driver
- [ ] should install the CSI driver through the managed AKS addon: https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver

Currently we're using a managed identity that's associated with the Virtual Machine Scale-Set and is prone to errors (e.g. when either AKS or the key-vault receives changes).
- [ ] should use pod identities instead https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-identity-access

Should probably do this when we move Kubernetes deployment script to terraform. Blocked by https://github.com/HSLdevcom/jore4/issues/954

**Comment by ellinooraikaheimo** [comment]
Moved and to be completed in Azure DevOps backlog
