### ISSUE TITLE
Depending on the zoom level, different stop points are shown in the map view

### ISSUE THREAD

**Issue by jschummer** [HSLdevcom/jore4#787]
Tested with Google Chrome Version 101.0.4951.64 (Official Build) (64-bit) on Ubuntu

Steps to reproduce:

1. Sign in to Jore4
2. Go to the map view
3. Check which stops are shown on the map
4. Zoom out one level

Expected result:

The same stops are shown as with the previous zoom level (maybe some more on the areas, which were not visible previously).

Actual result:

Some stops (clusters of stops), which were previously visible, are hidden, and some stops, which were previously hidden, become visible.

**Comment by jschummer** [comment]
![image](https://user-images.githubusercontent.com/77336519/169833456-f26c7d00-cf61-4edb-9959-fd03c82b6efe.png)

**Comment by jschummer** [comment]
![image](https://user-images.githubusercontent.com/77336519/169833570-72e447d8-c1f6-4d9c-ad40-b2a092d28dba.png)

**Comment by eleksi** [comment]
This is most likely because there is a limit for number of stops fetched. Different stops are fetched for different zoom levels. The limit will be removed and this issue should be resolved.
