### ISSUE TITLE
Update UI to work with NodeJS 18

### ISSUE THREAD

**Issue by pallost** [HSLdevcom/jore4#799]
The current NextJS proxying does not work with the latest NodeJS 18 version. Probably it's enough if we just update NextJS package to the latest version to stay compatible

**Comment by culka** [comment]
Updating the UI to work with NodeJS 18 also requires updating other used libraries and changing the Node server configuration.

NodeJS versions pre-17 used IPv4 as the default routing method but newer ones use IPv6 and this apparently breaks a lot of references to localhost. Using the --dns-result-order=ipv4first command line option fixes some, but not all, of these problems.
