### ISSUE TITLE
Refine line styles and snap points when drawing  a route

### ISSUE THREAD

**Issue by juhakolari** [HSLdevcom/jore4#806]
There are some visibility issues when drawing a route. Also, the cursor does not indicate that the user is selecting a start and stop for the route.

Using a pin and darker lines tones would help.

[Updated snap points styles (Figma)](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=2333%3A80677)

<img width="504" alt="Screen Shot 2022-09-28 at 11 30 37" src="https://user-images.githubusercontent.com/77674841/192730092-4e66072e-a8a3-4910-bf54-43b1e5d3b25b.png">

**Comment by eleksi** [comment]
Unfortunately it seems like the library we are using does not support adding inner rectangle inside the outer one. Pretty much the only things we can play with are rectangle line width, color, opacity, dash array and rectangle size.
