### ISSUE TITLE
Add VIA point importing to jore3 importer

### ISSUE THREAD

**Issue by pallost** [HSLdevcom/jore4#840]
The contents of the Jore3 jr_via_nimet table are somewhat unclear. In Jore3, the route destination used to be stop-specific, while in Jore4 it is route-specific.

Check if this is stil the way to go, also check the slack thread: https://vincit.slack.com/archives/CNG9QULAH/p1655378849108369

Lets proceed with the logic "maaranpaa1" and "maaranpaa2" and iterate this further in the passenger information module.

**Comment by jschummer** [comment]
As discussed elsewhere, it would be good to use the `jr_via_nimet`-table's `maaranpaa2`-column's values.
