### ISSUE TITLE
Creating new version of existing stop fails at `GetRoutesBrokenByStopChange` request

### ISSUE THREAD

**Issue by tk-vincit** [HSLdevcom/jore4#851]
Steps to reproduce:
- Create new version of existing stop (e.g. H1212 with production data dump, perusversio, validity stars now, indefinite)

- Expected result: conflict occurs and it is shown to the user

- Current result: `GetRoutesBrokenByStopChange` request timeouts and weird error message is shown to the user.

Related to [#907](https://github.com/HSLdevcom/jore4/issues/907)

**Comment by jschummer** [comment]
This could only be reproduced by artificially causing a wait of 30 secs in the SQL-function called.

In that case, the following response could be seen:
```<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>Microsoft-Azure-Application-Gateway/v2</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
```

This needs more investigation if the amount of routes (journey patterns) causes this to be seen more often.
