### ISSUE TITLE
Fix bug all versions of same stop showing for route in map view stop list

### ISSUE THREAD

**Issue by eleksi** [HSLdevcom/jore4#860]
When viewing a route, if there are multiple versions of a stop that is on route, they are all listed in the stop list.

This was fixed for route editing, but when viewing a route the bug still exists.

Steps to reproduce:
- Have a stop that has multiple versions (e.g. standard and temporary) on a route (e.g. add extra temporary H1236 stop on top of seed data)
- Open that route in map view
- Click the route to see the stop list
- The stop list has the stop with multiple versions multiple times, even though the journey pattern contains it only once

![Kuva tilanteesta](https://user-images.githubusercontent.com/51695324/174278016-19a4f9d6-47d0-42aa-ad9d-641db806a61c.png)

**Comment by HenrikHartiala** [comment]
"This was fixed for route editing" only partly. It still shows the highlighting for all versions in the geometry.
