### ISSUE TITLE
Go through all current UI forms and check that the validation errors are displayed for all inputs

### ISSUE THREAD

**Issue by pallost** [HSLdevcom/jore4#899]
Should start using the new `<InputField>` component

**Comment by sr-vala** [comment]
- näyttääkö kaikki input kentät samalta (eli css on kunnossa)
- onko kaikki lomakkeet riittävän responsiivisia (jos ikkuna on kapeampi, niin lomakkeiden pitäisi uudelleenjärjestyä hyvin)
- onko kaikki lomakkeiden kentät validoitu (eli tulee pikkutähti ja punainen teksti jos vaadittu kenttä ei sisällä dataa)
