### ISSUE TITLE
Fix map E2E tests in the CI pipeline.

### ISSUE THREAD

**Issue by culka** [HSLdevcom/jore4#901]
Running map tests in the CI pipeline currently fails due to following webgl and certificate errors:

```
[9325:0802/113608.698121:ERROR:gl_utils.cc(319)] [.WebGL-0x166a00373800]GL Driver Message (OpenGL, Performance, GL_CLOSE_PATH_NV, High): GPU stall due to ReadPixels
```

```
9124:0802/113609.449828:ERROR:cert_verify_proc_builtin.cc(681)] CertVerifyProcBuiltin for digitransit-dev-cdn-origin.azureedge.net failed:
----- Certificate i=0 (OU=Cypress Proxy Server Certificate,O=Cypress Proxy CA,L=Internet,ST=Internet,C=Internet,CN=digitransit-dev-cdn-origin.azureedge.net) -----
ERROR: No matching issuer found
```

These should be fixed or a workaround implemented for them. 
Afterwards the e2e:skip-map option should be removed from the run-cypress-tests.yml workflow.

Depends on https://github.com/HSLdevcom/jore4/issues/902

**Comment by pallost** [comment]
Running e2e tests needs a stronger runner, the current github default runner does not have enough computing power and memory to run. Depends on https://github.com/HSLdevcom/jore4/issues/902
