### ISSUE TITLE
Fix broken routes check getting stuck when moving a stop

### ISSUE THREAD

**Issue by eleksi** [HSLdevcom/jore4#907]
Broken routes check times out when moving a stop that belongs to a route.

Steps to reproduce:
- Use test environment (https://test.jore.hsl.fi/)
- Find route 65 and view it in map
- The second stop of route 65 (direction 1) is H2061. Try to move it (Probably works with other route's stops as well)
- Time will pass until the request fails and a timeout error is shown in the console

Fix steps:
- [X] increase timeout in cloud envs
- [x] fix actual SQL query in Hasura
- [ ] optimize existing queries to not perform checks for routes not changing (validity time not overlapping with changing stop point's validity time)

Fixing this will probably fix #851 as well.

**Comment by jschummer** [comment]
Note that even with the fixes in place, stop changes might still take a very long time to complete in some cases.
