### ISSUE TITLE
As a developer, I'd like to be able to use the prod dump in my dev env easily

### ISSUE THREAD

**Issue by jschummer** [HSLdevcom/jore4#908]
This enables us to easily reproduce problems seen in production in our local dev envs.

- [ ] figure out where to store dumps (azure?)
- [ ] copy latest existing dump there from Google Drive (HSL Jore -> ... -> Vanhan Joren tietokanta -> ...)
- [ ] change UI repo dump import script to carry out the following steps: 1. shut down hasura 2. clean db (volume or otherwise) 3. import dump 4. start hasura

It's important that hasura has not run its migrations yet when the dump is imported. Importing the dump will overwrite Hasura's metadata, so already run migrations might leave stale artefacts.

**Comment by pallost** [comment]
the easiest solution would be to create a custom version of the start-dependencies.sh script that does the steps mentioned in the description
