### ISSUE TITLE
Fix route creation from showing two sets of cancel and save buttons (map footer & modal footer)

### ISSUE THREAD

**Issue by HenrikHartiala** [HSLdevcom/jore4#918]
When user is in map view and presses "Draw route", we are showing two sets of save and cancel buttons. This is due to the flow of the route creation in which the user first inputs the metadata of the route in the modal and then "saves" the modal (even though it does not actually save it to database and this button should be called "next" etc.). After the metadata the user will draw the route and then save it or cancel the whole process.

The issue here is that when the modal is opened, the save and cancel buttons of the whole process is already shown in the map footer. Currently if you press 'Cancel' on the map footer, it won't close the modal and the creation process goes in to corrupted state. Even if this map footer's 'cancel' button would close the modal, we still have two sets of buttons. 

I suggest that we at least keep the save and cancel buttons in the map footer hidden as long as the map modal is open, and maybe even hide the map footer for that time, to give the modal a little bit more space.

**Comment by juhakolari** [comment]
When showing a modal on top of the map, a transparent layer (e.g. Black 30%) should be on top of the rest of the screen (map area, header, footer). The user focuses on the modal; the header and footer options should no be operable. [An example of the layer in Figma](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=5408%3A306876).
