### ISSUE TITLE
Stop point dialog route list is difficult to read

### ISSUE THREAD

**Issue by jschummer** [HSLdevcom/jore4#922]
When a stop point is to be removed or a change is made to a stop, which requires the stop to be removed from certain routes, the user is displayed a list with the routes affected.

That list is unreadable, because it contains the same route label multiple times (as many as there is route instances?) and the route list is overshooting the modal.

![Image](https://user-images.githubusercontent.com/77336519/185912981-2f18f083-41e8-47a6-beb3-db5213b718f8.png)

Steps to reproduce:

1. Open line 23 on the map in https://test.jore.hsl.fi
2. Select e.g. stop H2127 (Alppikatu)
3. Press the delete button

**Comment by tk-vincit** [comment]
Note from backlog refinement: the same problem probably occurs also when stop is moved.
