### ISSUE TITLE
Indicate route priority in map view

### ISSUE THREAD

**Issue by eleksi** [HSLdevcom/jore4#924]
There is no indication in map view about which is the priority of route shown.

For example color coding similar to list view could be added to the window showing info about route and stops.

- Swap label and name texts in route information modal (like in figma)
- Level top of direction badge with top of text

- Add dark gray draft icon after label text, if route is draft. Ask about the new logo file from Juha.
- Add yellow timer icon ("temporary"-logo) after label text, if route is temporary. Add "temporary: (validity period)" to alt text

**Comment by tk-vincit** [comment]
Comment from backlog refinement meeting:

@juhakolari could you please add figma link about this?

**Comment by HenrikHartiala** [comment]
Additional info about this for @juhakolari. I think we already discussed this in the meeting last week(or this week?) that the map list views should have more indications for route priorities and validity dates. We should also add these for stops in map view as well, so if you have the time to make designs for stops as well.

I think we would benefit if the popup windows and the list views in map had indicators / info about the priorities and validity dates. Maybe there were something else as well?

Stops info popup already has the validity dates and priority indications, but do we need those to be reflected to the map markers too?
