### ISSUE TITLE
Document how to deploy a new version of a microservice with flux

### ISSUE THREAD

**Issue by pallost** [HSLdevcom/jore4#928]
For now, it's only documented how to deploy a new microservice. (https://github.com/HSLdevcom/jore4-flux#deploying-a-new-microservice) It's however a slightly different process to deploy a new version of an existing microservice. This should be documented.

**Comment by HenrikHartiala** [comment]
Before vacation, added wip commit to document-auto-deploy branch in flux. Not much there yete, but I can continue with this after vacation. If in hurry with this documentation, feel free to do this.
