### ISSUE TITLE
As a user I want to select routes

### ISSUE THREAD

**Issue by ellinooraikaheimo** [HSLdevcom/jore4#943]
MVP user story from the Timetables module. The user can make different searches for routes, and select either all or desired routes. Later in a different ticket, the user can export these selections.

![Image](https://user-images.githubusercontent.com/77675592/188880545-cf2eff74-8944-45ed-a69b-2ad99259f75d.png)

In the Routes and lines main page, the user can search and select routes with the following logics:
* Typing 9841 to receive all the routes for that line. 
* Typing 4* to receive all the routes in Vantaa. (iterate the possibility with HSL, maybe with Petri Selkisalo)
* Using the tickboxes for further selections regardind the priorities (select all, clear all, manual selections)
* Specify how to select all the routes and lines to be able to mass export everything (iterate with design if needed)

Figma: https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=6445%3A310727

Route search functionality extension split to separate issue: #984

**Comment by jschummer** [comment]
Before implementing "Typing 4* to receive all the routes in Vantaa" make sure that also in Jore4 line numbers will be prefixed with communal numbers the same way as in Jore3 (1 = Helsinki, 4 = Vantaa) or if the "transport target" field should be used as a separate search criterion.
