### ISSUE TITLE
As a user I want to receive Hastus import notification

### ISSUE THREAD

**Issue by ellinooraikaheimo** [HSLdevcom/jore4#948]
MVP user story from the Timetables module. User should get an information how the import took place. MVP level notifications are enough at first, later a more detailed summary of the import will be shown to the user. 

User will get a toaster informing that the import was either successful or unsuccessful.

Relates to #1044 and #1070 #1016 #947 We should know at least how the staging timetables are represented, might not need the microservice itself.

**Comment by HenrikHartiala** [comment]
If this ticket is about giving toast notification when importing, then this is already done.

![Image](https://github.com/HSLdevcom/jore4/assets/82645403/2a6133f9-392c-4b74-8fd7-d80298065aaa)
![Image](https://github.com/HSLdevcom/jore4/assets/82645403/7d403ec7-2afe-4639-8022-a4a8a94bb486)
