### ISSUE TITLE
As a user I want to see the routes basic day type timetables

### ISSUE THREAD

**Issue by ellinooraikaheimo** [HSLdevcom/jore4#950]
MVP user story from the Timetables module. In the routes timetable view, the user can see the different day types. 

The basic day types (peruspäivätyypit) are: Ma-To, Pe, La-Su. These are color coded with green. Discuss with HSL (Jenö), whether these are always the options or whether the user should be able to have variation possibility to set e.g. Ma-Ke, To, Pe, La-Su. 

![Image](https://user-images.githubusercontent.com/77675592/188841158-1ac7d215-dfef-4187-81ba-2bdd25343bcd.png)

User can see what is the validity period of the day type.

Figma, Day Types: https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=3238%3A257190 

Blocked by #681, creating the data model for timetables.
If not easy to make, split out from this ticket: the amount of departures, and showing the first and the last departure time

**Comment by tk-vincit** [comment]
UI is implemented within this ticket. Rest of the work continues in #1027
