### ISSUE TITLE
Change jore4-flux repository to be private

### ISSUE THREAD

**Issue by pallost** [HSLdevcom/jore4#952]
Currently the jore4-flux repository is public which is a bit of a security risk given that it contains the kubernetes manifests. To be able to make it private:
- [x] should get the flux controller to log in to github to be able to fetch the manifests (currently Flux can see it without logging in)
- [x] should change start_dependencies-scripts of various repos to use `gh` tool to download e2e releases
- [ ] get the CI workflows to be able to access the flux repo contents (via its actions)
- [ ] should ask HSL IT support to set the repository to private

In the future, we should probably also move this repository to Azure DevOps, however we already have lots of github workflows and converting those to Azure DevOps pipelines is a major effort. This is not in the scope of this ticket.

**Comment by jschummer** [comment]
According to what we found out, it should be possible for other jore4-repositories' workflows to access the jore4-flux actions. (No organization policy seems to be  preventing this.)

Therefore, it should be enough in point 2 to make the jore4-flux workflows able to access the jore4-flux repo's releases. (Either manually with a deploy key or by using the 'gh' tool or similar.)

**Comment by jschummer** [comment]
Changes of the ui, flux, hastus, hasura, and importer -repositories' start_dependencies-scripts are available in PRs: https://reviewable.io/reviews/hsldevcom#q=-label:dependencies%20docker-compose%20download%20script

These are still lacking the CI-changes outlines above and therefore CI runs fail for some of them.
