### ISSUE TITLE
Move Kubernetes provisioning script from ARM templates to Terraform script

### ISSUE THREAD

**Issue by pallost** [HSLdevcom/jore4#954]
Currently the Kubernetes provisioning script is done with ansible + ARM templates. It's quite flaky and needs several reruns to create all the resources and set up all the role bindings. Also there are multiple tasks to update Kubernetes's version, its key-vault addon, change its network controller to kubenet, etc. It would be probably easier to just do all these changes while also migrating the IaC script to Terraform.

HSL promised to provide an example Kubernetes Terraform script around the end of October 2022.

**Comment by pallost** [comment]
- Should take the HSL terraform modules into use (found from Azure DevOps)
- Could try to use the aztfy tool for generating initial configuration (and then refactor it slowly to use HSL or custom modules)

**Comment by jarkkoka** [comment]
A tool to bring existing Azure resources under Terraform's management

https://github.com/Azure/aztfexport

**Comment by jarkkoka** [comment]
Suggestion:

1. Fix Azure `test` enivronment
2. Create Terrafrom IaC script.
3. Test Terrafrom IaC script in Azure `playg` environment.

**Comment by ellinooraikaheimo** [comment]
Pending Terraform experimentation (#1290)

**Comment by ellinooraikaheimo** [comment]
Moved and to be completed in Azure DevOps backlog
