### ISSUE TITLE
Switch Kubernetes network adapter to kubenet

### ISSUE THREAD

**Issue by pallost** [HSLdevcom/jore4#957]
The current azure CNI network is not sustainable anymore as we ran out of IP addresses. Should switch to using kubenet networking

Userful information:

- https://learn.microsoft.com/en-us/azure/aks/configure-kubenet#overview-of-kubenet-networking-with-your-own-subnet
- https://learn.microsoft.com/en-us/azure/aks/concepts-network

Should probably do this when we move Kubernetes deployment script to terraform. Blocked by https://github.com/HSLdevcom/jore4/issues/954

**Comment by ellinooraikaheimo** [comment]
Pending Terraform experimentation (#1290)

**Comment by ellinooraikaheimo** [comment]
Moved and to be completed in Azure DevOps backlog
