### ISSUE TITLE
Automate flux deployments

### ISSUE THREAD

**Issue by pallost** [HSLdevcom/jore4#962]
Set up flux repository's pull requests to get merged automatically. Warning: only merge pull requests that are done by the auto-deploy script, not the user pull requests

Requires research and possibly a robot.

**Comment by tk-vincit** [comment]
This is done now.
Because we are using:
`merge-method: MERGE`, on had to disable
```
Require linear history
Prevent merge commits from being pushed to matching branches.
```
setting from repository settings. Otherwise we would just get very confusing `An error occurred while performing auto-merge.` error message on pull request page, without any additional details.
