### ISSUE TITLE
Research: Take temporal tables into use in Routes & Lines module

### ISSUE THREAD

**Issue by jschummer** [HSLdevcom/jore4#987]
Decide whether to use temporal tables function or extension. Create implementation tickets.

Old specification:

This is needed when the user should be presented an indication whether a route (or any of its components) has been changed after timetables have been planned in Hastus. (More specifically: whether a route has been changed after the Hastus export has been performed.) In theory, collecting only timestamps instead of history data would suffice, but the history data is collected using almost the same effort.

History data should be collected for the following tables:
- line
- route
- infra_links_along_route
- journey_pattern
- scheduled_stop_point_invariant
- scheduled_stop_point
- scheduled_stop_point_in_journey_pattern

If triggers are needed, care needs to be taken to run triggers in the right order (constraint triggers need to be run first and the transaction needs to be aborted in case a constraint is not satisfied). Prefixes should be employed to ensure this.

[Change history summary in Figma](https://www.figma.com/file/dsNMixsO1558hCX0XzRDrc/Bus-stops-%7C-JORE-4.0-UX?type=design&node-id=1896%3A78433&t=YpTaINsx6NubuLns-1). 

Related to https://github.com/HSLdevcom/jore4/issues/1192
Blocked by #1308

**Comment by ellinooraikaheimo** [comment]
In the scope of this ticket, do the research and decisions how this should be implemented technically. Discuss in a-rinki 31.8. After the decisions made, create new tickets for implementation. Note, that the frontend (user stories) tickets are created separately. Specify this ticket to match the work to be done, at the moment it is unclear. Ping @culka @juhakolari
