### ISSUE TITLE
Revisit Hastus integration article in wiki

### ISSUE THREAD

**Issue by jarkkoka** [HSLdevcom/jore4#993]
[Hastus integration article](https://github.com/HSLdevcom/jore4/blob/main/wiki/hastus-integration.md) in wiki is last updated in January 2021. It should be re-visited now that implementation of timetables is progressing. Decide what to do with it.

This documentation is primarily targeted to developers, for sharing knowledge. Also, these decisions are freshly in mind. 

Note: Consider what we can put here since it's public. We cant share Giro's materials e.g.

**Comment by pallost** [comment]
In my opinion it's still up-to-date and does not need any changes
